kubeshop/botkube

helm/kubeops/values.yaml, pkg/controller/controller.go, pkg/events/events.go, pkg/execute/executor.go, pkg/filterengine/filters/ingress_validator.go, pkg/notify/notify.go, pkg/notify/slack.go
Fixes: #2 
- Send bot start/stop messages to slack channel
- Fix timestamps in delete notifications
=> Send bot start/stop messages to slack channel

deploy-all-in-one.yaml
Fixes: https://github.com/infracloudio/botkube/issues/9
=> Add yaml specs to deploy with kubectl command

helm/botkube/Chart.yaml
Helm lint recommends that charts include an icon. I added one that was already hosted on the website
```
➜  botkube git:(master) ✗ helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, no failures
```
```
➜  botkube git:(master) ✗ cat Chart.yaml 
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
icon: https://www.botkube.io/images/botkube.ico
name: botkube
version: 0.1.0
➜  botkube git:(master) ✗ helm lint .
==> Linting .
Lint OK
1 chart(s) linted, no failures
```
=> Adding icon so chart passes `helm lint`

config.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/slack/slack.go
=> Added check slack channel in config, when get message 

README.md
- This makes is really easy to find the website as well as Slack when
someone visits the repository
=> Add badges for Slack and docs

deploy-all-in-one.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml, pkg/controller/controller.go, pkg/logging/logging.go, pkg/notify/elasticsearch.go, pkg/utils/utils.go
Fixes: https://github.com/infracloudio/botkube/issues/66
=> Add new env var LOG_LEVEL to set logging levels

.github/PULL_REQUEST_TEMPLATE.md
- Makes it easy for contributors to create a new PR
- It will ensure that the issue being solved by PR gets referenced in
the Pull Request body
- Taken from
https://github.com/transtats/transtats/blob/devel/.github/PULL_REQUEST_TEMPLATE.md
which is Apache 2.0 licensed
=> Add GitHub Pull Request template

pkg/controller/controller.go, pkg/execute/executor.go, pkg/filterengine/filterengine.go, pkg/filterengine/filters/image_tag_checker.go, pkg/filterengine/filters/ingress_validator.go, pkg/filterengine/filters/pod_label_checker.go
fixes #71 
Usage:
```
@BotKube filters list : list all filters
@Botkube filters disable <filter-name> : Disable perticular filter
@Botkube filters enable <filter-name> : Enable a filter
```
Next action items:
- Update steps to create custom filter in botkube-docs
- Update BotKube help with filter command documentation
=> Add support to manage filters with @BotKube command

helm/botkube/Chart.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
- If image.tag is set in values.yaml then that tag is used, otherwise
falls back to Chart version
- This makes easy to deploy images tagged with different names which
are not according to sem ver 2 i.e. 'latest' or other valid
container image tags
fixes #88
=> [helm chart] make image tag configurable

.travis.yml
- Makes sure that image on Docker hub is updated only for commits to
develop branch and not for PRs
- ref:
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
- As PRs from contributors don't have access to secrets, builds are failing with error like this one, https://travis-ci.org/infracloudio/botkube/builds/533893897#L580
=> [Travis CI] don't push container image for PR builds

Makefile
Fixes #90   
Updated Makefile targets to:  
`make build` : to build binary
`make container-image`: to build docker image
=> New make target `container-image` to build docker image

Makefile, hack/release.sh
Steps for making release:
1. Create github access token
2. Run `GITHUB_TOKEN=<TOKEN> ./hack/release.sh`
The `./hack/release.sh` script will -
- update deployment yamls and helm chart
- generate changelog
- build and push docker image
- create and push git tag
3. Draft release on github UI
Fixes #69
=> Add script to publish release and auto generate CHANGELOG

helm/botkube/values.yaml, pkg/controller/controller.go, pkg/events/events.go, pkg/filterengine/filters/job_status_checker.go
- Add JobStatusChecker filter to send Job success notifications when configured to watch update events
- Add missing TimeStamps in error events
Fixes #95 and #107 
BotKube configuration for `jobs`:
```
- name: jobs
namespaces:
- all
events:
- delete
- update
- error
```
1. Job success notification
2. Job Failure notification
3. Error events
=> Add JobStatusChecker filter and fix timestamp for error events

.travis.yml
Currently, travis CI build seems to be broken. Since we have changed make target to build a container image, need to update travis CI script accordingly.
From travis job log (https://travis-ci.org/infracloudio/botkube/builds/550685578):
```
$ if [[ "$TRAVIS_BRANCH" == "develop" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push infracloud/botkube:latest; fi
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
The push refers to a repository [docker.io/infracloud/botkube]
An image does not exist locally with the tag: infracloud/botkube
```
=> Fix make target in travis CI to build image

cmd/botkube/main.go, pkg/bot/mattermost.go
This Commit,
- starts mattermost bot as goroutines
- replaces `Debug` with `Debugf` in mattermost.go (suggested by govet)
=> Fix minor bugs

.travis.yml, Makefile, hack/unit-test.sh
This PR
- Adds make target to run unit tests
- Enable unit test check in travis
Signed-off-by: Shovan Maity <shovan.cse91@gmail.com>
Patched 
- Rebased `imazik:enable-unit-test` onto `infracloudio:develop` 
- adds `unit-test` to `make release`
Signed-off-by: Aananth K <aananthraj1995@gmail.com>
Fixes #144
=> [unit test] Enable Unit test and add target in Makefile

config.yaml, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/controller/controller.go
This commit,
- adds `config.settings.configwatcher` to enable/disable config watcher
- updates info in all config.yaml files
Fixes #150
=> Add flag to control Config Watcher

pkg/events/events.go
This Commit
- bug fixes the event notification skips occurring in old resources
Fixes #147
=> Unskip error and update events for old resources

Makefile, pkg/events/events.go, pkg/filterengine/filters/object-annotation-filter/object_annotation_checker.go, pkg/filterengine/filters/object-annotation-filter/object_annotation_checker_test.go, pkg/notify/mattermost.go, pkg/notify/slack.go, pkg/utils/utils.go
This commit, 
- enables filtering of events based on annotations present in objects at run time.
- annotation `botkube.io/disable: true` disables event notifications for the annotated object
- annotation `botkube.io/channel: <channel_name>` sends events notifications of the annotated object to the mentioned channel.
- adds func `utils.ExtractAnnotations()`. It extracts annotations from Event.InvolvedObject.  Extracted Annotations are then added to the event.Metadata.Annotations
- implements individual actions using internal functions.
- adds unit tests for internal functions.
- replaces `utils.Init()` with `InitialiseKubeClient()` to decouple `config.yaml` and `KubeClinet` dependencies from unit testing
Fixes #132
Adding `botkube.io/channel: <channel_name>` …
=> [feature] Add Object Annotation filter, Fixes #132, #133

config.yaml, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, go.mod, helm/botkube/values.yaml, pkg/controller/controller.go, pkg/events/events.go, pkg/filterengine/filters/ingress_validator.go, pkg/filterengine/filters/job_status_checker.go, pkg/utils/cmp.go, pkg/utils/cmp_test.go
This PR,
- enhances update event notifications with details of what Spec is getting changed
- adds custom `SpecDiffReporter` and `utils.Diff()` method.
- adds update events in all config.yaml files
- excludes namespace field from namespace independent resource events
Fixes #131
Fixes #135 
Fixes **excludes namespace field from namespace independent resource events**
- secret being namespaced gets namespace field
=> Enhance Update Events with resource spec diff and Change event message formats

helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
Adding Support for Basic Proxy
Need a proxy configured to use the proxy value. If statement in deployment.yaml will make sure deployment doesn't fail, if proxy is not being used
Fixes #155
=> add proxyURL, deployment env variable if-loop

config.yaml, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/controller/controller.go, pkg/filterengine/filters/namespace-filter/namespace_checker.go, pkg/filterengine/filters/namespace-filter/namespace_checker_test.go, pkg/utils/utils.go
This PR, (updated)
- adds support for ignoring certain namespaces while watching all namespaces.
- replaces `Namespaces []string` with `Namespaces.Include []string`
- adds `Namespaces.Ignore []string` ( optional / omitempty ) filed to ignore namespaces when Namespaces.Inculde contains "all"
- adds unit test cases for isNamespaceIgnored()
Fixes #128 
This could allow as to watch all namespaces except a list of namespaces to ignore.
Example:
```yaml
resources:
- name: services
namespaces:
include:  
- all
ignore:
- development
- staging
events:
- create
- delete
- error
```
This config watches services of all namespaces except namespaces `development` and `staging`
=> [feature] Add support for ignoring namespaces

pkg/config/config.go, pkg/controller/controller.go, pkg/events/events.go, pkg/filterengine/filters/node_event_checker.go
This PR,
- Allows  kubernetes events of `Warning` Type as `ErrorEvents`
- Allows kubernetes events of `Normal` Type as Insignificant `InfoEvents`
- Adds `NodeEventsChecker` filter to check for Node InfoEvents with critical reasons like `NodeNotReady` ,`NodeReady`.
- `InfoEvents` with critical reasons are promoted as significant Node `ErrorEvents`
- Post events filtering, unpromoted Insignificant `InfoEvents` are skipped. 
Fixes #134
**Preview**
=> Node Level Critical Events filter

pkg/notify/elasticsearch.go
This PR,
- Fixes cluster filed not being populated in ES.
- adds  `ClusterName` to `ElasticSearch` type.
Fixes #59 (issues reported in #59)
=> Fix cluster field not being populated in ES

build/Dockerfile, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
This PR,
- runs botkube containers as Non Privileged user
- adds `securityContext` filed to containers in all yaml files.
- adds `securityContext` fields to helm charts
Fixes #161
=> Run containers using Non Privileged user

cmd/botkube/main.go, config.yaml, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/notify/webhook.go, pkg/notify/webhook_test.go, test/e2e/command/botkube.go, test/e2e/command/kubectl.go, test/e2e/e2e_test.go, test/e2e/env/env.go, test/e2e/filters/filters.go, test/e2e/notifier/create/create.go, test/e2e/utils/utils.go, test/e2e/welcome/welcome.go, test/webhook/server.go, test/webhook/types.go
**Modify return type as pointer:**
This commit,
- modifies return type of  GetLastSeenSlackMessage to pointers.
**Add support for Webhooks:**
This Commit,
- Adds support for event notifications through `Wehbook` 
- updates configs in all yaml files
- updated helm charts
- adds unit tests for webhook notifier
- adds integration test webhook notifier
- adds test/webhook package to enable integration testing.
**Preview**:
```
{
"meta": {
"kind": "Pod",
"name": "command-app-1",
"namespace": "default",
"cluster": "demo"
},
"status": {
"type": "create",
"level": "info",
"reason": "",
"messages": [
"Resource created\n"
]
},
"summary": "Pod `command-app-1` in of cluster `demo`, namespace `default` has been created:\n```Resource created\nRecommendations:\n- :latest tag used …
=> Add support for Webhooks

pkg/events/events.go, pkg/notify/mattermost.go, pkg/notify/slack.go, test/e2e/filters/filters.go, test/e2e/notifier/create/create.go
- Modify notification message format to make them more readable
**notifType=short**
**notifType=long**
=> Make notification messages more readable

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/templates/clusterrole.yaml, helm/botkube/templates/podsecuritypolicy.yaml, helm/botkube/values.yaml
- When attempting to install either the develop branch or v0.8.0 of botkube via helm, the botkube deployment pod crashes repeatedly due to a security permissions issue. From what I can tell, the botkube docker image references a system user by name rather than UID, which may violate default pod security policies in restricted environments (at least in v0.8.0). In addition, the pod appears to use [unsafe sysctls](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls), as this setting is required for the pod to run without crashing.
- After making the above changes and restarting the botkube pod in CrashLoop backoff, the pod was able to run continuously and began working correctly. We were able to issue kubectl commands to botkube …
=> Add pod security policy so botkube works in restricted clusters

.travis.yml, go.mod, go.sum, pkg/bot/slack.go
=> Update slack dep to work with latest Slack api changes

pkg/notify/mattermost.go
Add colors based on notification type to the attachments
=> Add colors to Mattermost notification attachments

.gitignore, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/config/config.go, pkg/execute/executor.go, resource_config.yaml, test/e2e/command/kubectl.go, test/e2e/e2e_test.go, test/resource_config.yaml
This flag will control user's access to botkube via configured channel. If set to true, it will allow user to talk to botkube only through configured channel. In other case, botkube will be accessible from all channels.
Signed-off-by: Mahendra Bagul <mahendra@infracloud.com>
Fix for https://github.com/infracloudio/botkube/issues/235
=> Added restrictAccess flag to enable/disable behavior of botkube. 

pkg/execute/executor.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This commit fix the bug 230 which shows redundant error message
when deployed in miticluster, added check for cluster name and
created new function to get cluster name from kubectl command
=> Checked cluster name before executing kubectl command

hack/release.sh, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
=> helm fixes

pkg/.mergify.yml
Enable auto merge using Mergify on approval
Workflow:
- Developer opens a PR
- Reviewer approves the changes and adds `ready-to-merge` label
- Mergify runs CI again and merges the PR
- Mergify holds the auto merge if `hold-off-merging` label is set
=> Enable auto merge using Mergify on approval

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/config/config.go, pkg/execute/executor.go, resource_config.yaml, test/e2e/e2e_test.go, test/resource_config.yaml
This Commit,
- Adds `kubectl.Enabled`, `Kubectl.DefaultNamespace` to `Config.Settings` to configure default namespace, under which all  botkube kubectl commands will be executed by default.
- changes `Settings.RestrictAccess` into `Settings. Kubectl.RestrictAccess` 
- updates all config.yaml files
Fixes #176
**Preview**:
```yaml
settings:
kubectl:
enabled: false
defaultNamespace: default
restrictAccess: false
```
=> Configure default namespace for kubectl cmds through config

helm/botkube/templates/deployment.yaml
Currently, even if I set toleration values in the `values.yaml` file they are not being picked up as there is no toleration's block in `deployment.yaml` template, so adding the toleration's block.
Tested as below:
` helm template --name botkube .`
```
volumes:
- name: config-volume
projected:
sources:
- configMap:
name: botkube-configmap
- secret:
name: botkube-communication-secret
securityContext:
runAsUser: 101
runAsGroup: 101
tolerations:
- effect: NoSchedule
key: nodeType
operator: Equal
value: OnDemand
```
`helm3 template botkube .`
```
volumes:
- name: config-volume
projected:
sources:
- configMap:
name: botkube-configmap
- secret:
name: botkube-communication-secret
securityContext:
runAsUser: 101
runAsGroup: 101
tolerations:
- effect: NoSchedule
key: nodeType …
```
=> add tolerations in the deployment.yaml template

pkg/execute/executor.go
Default executor is expecting more than 2 arguments.
Fixed number of arguments needed to 1.
Fixes #300
=> Allow kubectl commands wihtout namespace and without cluster-name

comm_config.yaml, go.mod, go.sum, pkg/config/config.go, pkg/notify/elasticsearch.go
Allows user to specify if Elasticsearch is hosted on AWS
- configuration fields have been added to specify if Elasticsearch is hosted on AWS
Includes feature which would allow botkube to send Kubernetes events to Elasticsearch hosted on AWS
* Uses AWS V4 signature to sign the http request
* Uses environment variables to pick AWS configurations
Secondly creates new index per day with index name suffixed as -DD-MM-YYYY
Fixes #299 
Fixes #283
=> adding feature to support AWS Signing and creating new index per day

comm_config.yaml, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/templates/serviceaccount.yaml, helm/botkube/values.yaml
adding config values for helm deployments
adding config values for helm deployments
Fixes #XXX
=> Add aws config in helm values

comm_config.yaml, pkg/config/config.go, pkg/notify/elasticsearch.go
Allow using AWS role or EC2 Instance role to generate session tokens for AWS credentials.
=> allow using AWS role or EC2 Instance role for Elasticsearch Auth

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
Priority class support for helm deployment
=> Priority class support for helm deployment

cmd/botkube/main.go, go.sum, pkg/config/config.go, pkg/events/events.go, pkg/filterengine/filters/node_event_checker.go, pkg/notify/elasticsearch.go, pkg/notify/mattermost.go, pkg/notify/notify.go, pkg/notify/slack.go, pkg/notify/webhook.go, pkg/notify/webhook_test.go, test/e2e/e2e_test.go, test/e2e/utils/utils.go
In the notifier, we send events by creating a new connection to the communication medium on every new event. We can reduce the number of connections by sending messages via the Bot interface.
Fixes #270
=> Refactor notifier to use Bot interface to send notifications

pkg/execute/executor.go
This should fix panic on empty command. 
Bot will send the default message for the executor Platform (in my case its mattermost)
Sent empty command to botkube via mattermost (type @botkube)
> Command not supported. Please run /botkubehelp to see supported commands.
or at least nothing 
`panic: runtime error: index out of range [0] with length 0
goroutine 28 [running]:
github.com/infracloudio/botkube/pkg/execute.(*DefaultExecutor).Execute(0xc000a11020, 0x0, 0x0)
go/src/github.com/gohumble/botkube/pkg/execute/executor.go:191 +0xe13
github.com/infracloudio/botkube/pkg/bot.(*mattermostMessage).handleMessage(0xc000b75de8, 0xc0003d1940, 0x1a, 0xc00046b7c0, 0x5, 0xc00046b7cc, 0x4, 0xc00046b120, 0xd, 0x1, ...)
go/src/github.com/gohumble/botkube/pkg/bot/mattermost.go:154 …
=> Fix crash on empty command in mattermost integration

pkg/execute/executor.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/command/botkube.go, test/resource_config.yaml
Added new botkube command to list all the supported commands, @botkube commands list
Below are the changes
made changes in executor.go to handle newly added command  
added common method in utils.go to format the allowed commands  
Fixes https://github.com/infracloudio/botkube/issues/312
=> Added '@Botkube commands list' to show all the supported kubectl cmds 

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, resource_config.yaml
Update resource in deployment manifests with G/V/R format
Fixes #331
=> Update resource in deployment manifests with G/V/R format

pkg/utils/diff.go
Jsonpath eval fails if fields are not set in old obj by the time event issued. Ignore error in that case and continue message construction
=> Fix for missing update diff for first update event

CONTRIBUTING.md
=> Fix installation steps in CONTRIBUTING.md

test/e2e/e2e_test.go, test/e2e/notifier/delete/delete.go, test/e2e/utils/utils.go
Added skip delete event test case that should be skipped for resources which are not configured for delete event in test config.
Modified the resource configuration map AllowedEventKindsMap and removed delete event for pod.
Fixes test case - Validate delete events are skipped when delete event is not configured for a resources in test config. e.g events: [create, update, error] of issue #354
=> added testcases for skip delete event for resources not configured

README.md
ISSUE TYPE
SUMMARY
Add Licence reference badge in README
Add licence related info in README
Add Licence reference badge in README for getting visible at first glance
Add licence related info in README
=> [Documentation]Add repo licence info and badge

deploy-all-in-one.yaml, pkg/controller/controller.go, pkg/events/events.go, pkg/filterengine/filters/image_tag_checker.go, pkg/filterengine/filters/ingress_validator.go, pkg/filterengine/filters/pod_label_checker.go, pkg/utils/utils.go, test/e2e/command/botkube.go
=> Fix spelling

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/sample-res-config.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/filterengine/filters/namespace_checker.go, pkg/filterengine/filters/namespace_checker_test.go, resource_config.yaml, test/resource_config.yaml
Fixes issue #295
This change allows to ignore whole sets of namespaces using the asterix expansion. It still does the exact match check for all the namespaces (separated by comma in config), but if it contains a `*`, it's actually replaced with `.*` and passed to `regexp.MatchString` to do the job.
PR also contains couple of very simple test cases.
deps:
`namespace_checker.go` now imports also `regexp`
Fixes #295
It's my very first golang code, so please let me know if it's not idiomatic go :cookie:
=> Add a support for ignoring the events from a namespace that matches regexp

pkg/notify/webhook.go, pkg/notify/webhook_test.go, test/e2e/env/env.go, test/e2e/notifier/update/update.go, test/e2e/utils/utils.go, test/webhook/server.go
This Commit, 
- Fixes build failure due to e2e tests
Fixes #384
=> Bug Fix e2e tests

test/e2e/notifier/delete/delete.go, test/e2e/utils/utils.go
Adds test case - Validate delete events are handled with only events: [delete] config for a resource.
Fixes part of #354
=> Added test case to validate delete event

pkg/controller/controller.go, pkg/utils/utils.go, test/e2e/notifier/create/create.go, test/e2e/notifier/delete/delete.go, test/e2e/notifier/update/update.go, test/e2e/utils/utils.go
Added skip delete event test case that should be skipped if event occurred for a resource which is not added in test configuration.
Modified AllowedEventKindsMap to removed the v1/services resource
Fixes test case - Validate that delete events are skipped when an event occurs for a resource which is not added in resource_config of issue #354
=> added test for skip delete event when resources are not added in test_config

test/e2e/e2e_test.go, test/e2e/notifier/error/error.go, test/e2e/utils/utils.go
- Validates error events are skipped when the error event is not configured for a resource in test config.
- Validate that error events are skipped when an event occurs for a namespace which is not added in resource_config
Fixes part of #340
=> Added test case to validate error event

helm/botkube/templates/clusterrole.yaml
Correctly indent RBAC rules. It was previously throwing an error when enabling both psp and rbac at the value level. 
Fixes #325
=> fix(charts): correct indentation for rbac rules

hack/runtests.sh, pkg/bot/slack.go
adding support for botkube to interact in slack threads
I did update the test bash script that would not run on my zsh shell on my mac.
I Also wanted to add some unit tests but the Slack test server does not support thread messages.
Fixes #422
=> feat(slack): add thread support

pkg/notify/elasticsearch.go
Elasticsearch Indices will be created with timestamp suffix
=> [ES] indices to be created with daywise timestamp

pkg/execute/executor.go, test/e2e/command/botkube.go
Checks for the cluster name for the `commands list` command if passed.
Fixes #420
=> Cluster name for commands

pkg/notify/discord.go
Use correct timestamp in Discord event notification 
Fixes #441
=> Fix notification timestsamp in Discord

pkg/events/events.go, pkg/filterengine/filters/namespace_checker.go
Apparently the wrong member was used to check the resource name. I don't
know how resillient this patch is, but it works for most of the part.
Fixes #419
=> Fixed namespace checker to use the correct name

pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/bot/teams.go, pkg/bot/utils.go
Use uniform `codeblock` format for command responses across different integrations
=> Use uniform response format

pkg/config/config.go, pkg/execute/executor.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Resolved issue of DefaultNamespace value is not getting populated in config and appending default namespace if another namespace is already passed
=> corrected defaultNamespace population and avoid appending defaultnamespace if already passed 

pkg/execute/executor.go, pkg/utils/utils.go, pkg/utils/utils_test.go
When clustername is passed to botkube from command and if that clustername contains valid domain then slack automatically adds <http:// to the url  
eg.  
if command is `@BotKube get pods --cluster-name xyz.alpha-sense.org`  then in botkube we get cluster name as `<http://xyz.alpha-sense.org|xyz.alpha-sense.org>`
Added small logic in executor code to remove the unwanted string
Fixes https://github.com/infracloudio/botkube/issues/460
=> remove unwanted hyperlink text from command

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/README.md, helm/botkube/templates/deployment.yaml
Added code block in helmcharts to support imagepullsecrets
as a best practise changed the imagePullPolicy to "IfNotPresent"
Fixes #471
=> adding support for imagePullSecrets and pullpolicy to "IfNotPresent"

pkg/utils/diff_test.go
We wanted to add `updateSetting` for an annotation from the Kubernetes Apps SIG. This annotation contains dots and slashes. I wasn't sure which field to use, so I've updated the test to make it very clear that it requires the syntax of number 1:
1. `metadata.annotations.app\.kubernetes\.io\/version`
2. `metadata.annotations["app.kubernetes.io/version"]`
Fixes #XXX
=> Test and document adding updateSetting for complex annotation keys

build/Dockerfile
This fetches the current latest stable kubectl directly from the upstream.
An alternate approach would be to copy from `rancher/kubectl` but that requires explicit versioning.
Fixes #516
=> fix: download the correct arch-specific kubectl

build/Dockerfile
This release includes fixes for openssl CVE-2021-3711 and CVE-2021-3712.
https://alpinelinux.org/posts/Alpine-3.14.2-released.html
Fixes #523
=> Update Base Image to alpine 3.14.2

.github/workflows/artifacts.yml
New goreleaser versions doesn't allow builds with "latest" tags. This PR pins the goreleaser version in CI to prevent it from failure.
=> [CI] Fix goreleaser build with latest tags

helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
Allow to set deployment annotations in helm chart.
Fixes #536
I hesitated to use `extraAnnotations`, but when I look at other official helm charts most of the time they use different values for pods and deployments annotations. 
Imho we should also rename `extraAnnotations` to `podAnnotations` but would be a breaking change so I left it as it was.
=> feat(helm): allow to set deployment annotations

build/Dockerfile
Please make a release, maintainers!
Mandatory security update
Addresses:
| CVE-2021-42378 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42379 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42380 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42381 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42382 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42383 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42384 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42385 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42386 | HIGH | busybox | 1.31.1-r20 | 1.31.1-r21
  | CVE-2021-42374 | MEDIUM | busybox | 1.31.1-r20 | 1.31.1-r21
=> Update base image to address busybox CVEs

pkg/utils/utils.go
After using Botkube for some time, I found a large number of "not found" errors when querying logs for troubleshooting. 
Following the code, it turns out that these errors are caused by the Informer cache but are actually normal. Controller-runtime does a similar thing.
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go
```
// IgnoreNotFound returns nil on NotFound errors.
// All other values that are not NotFound errors or nil are returned unmodified.
func IgnoreNotFound(err error) error {
if apierrors.IsNotFound(err) {
return nil
}
return err
}
```
=> Ignore  error of type not found in resource

pkg/utils/utils.go
`strings.ToLower/strings.ToUpper` will have to allocate memory for the new strings, as well as convert both strings fully, even if they differ on the very first byte. On the other hand, `strings.EqualFold` compares the strings one character at a time. It doesn't need to create two intermediate strings and can return as soon as the first non-matching character has been found.
=> perf: Use `strings.EqualFold` for string comparison

.github/workflows/artifacts.yml, CONTRIBUTING.md, Makefile, hack/goreleaser.sh
The latest goreleaser doesn't support non-semver image tags. 
This PR replaces `latest` tags with `v9.99.9-dev` to support latest version of goreleaser
=> Replace latest tag with v9.99.9-dev in builds

pkg/events/events.go
The lastTimestamp field of the event is sometimes null and sometimes not empty, but these are normal, just because the old and new APIS are called differently. So we need to add a judgment here, using the EventTime field if lastTimestamp is empty
Fixes https://github.com/infracloudio/botkube/issues/548
=> fix: Failed to analyze an event whose lastTimestamp is null

.goreleaser.yml
project_name field was made mandatory in new goreleaser version, due to this make container-build was failing
added this field in .gorelease.yml to fix this issue
=> added project_name field

helm/botkube/README.md, helm/botkube/templates/extraobjects.yaml, helm/botkube/values.yaml
- Support extra K8s resources creation during Helm chart installation
Additional pull request that updates documentation: https://github.com/infracloudio/botkube-docs/pull/72
Resolves #561 
Clone this repository (check out the branch) - you can use https://cli.github.com/
Create namespace:
```bash
kubectl create ns botkube
```
Run a dry-run of botkube installation with custom values
```bash
cat > /tmp/values.yaml << ENDOFFILE
extraObjects: 
- apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: "{{ include \"botkube.fullname\" . }}-clusterrolebinding"
labels:
app.kubernetes.io/name: "{{ include \"botkube.name\" . }}"
helm.sh/chart: "{{ include \"botkube.chart\" . }}"
app.kubernetes.io/instance: "{{ .Release.Name }}" …
```
=> Support extra K8s resources creation during Helm chart installation

.gitignore, hack/release.sh
- Feature/Docs Pull Request
- Make the release script cross-platform
- Remove unnecessary step from the release script (it fails all the time, as the Goreleaser execution already creates GitHub release)
See also https://github.com/infracloudio/botkube-docs/pull/74/files
You can follow the instruction from the PR https://github.com/infracloudio/botkube-docs/pull/74/files to test the changes on your fork 🙂
=> Make the release script cross-platform

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/templates/deployment.yaml
- Fix writing cache for kubectl exec commands
Fixes #564 
Initially I wanted to reuse cache directory both for kubectl executor and cachedDiscoveryClient used for dynamic K8s client, to avoid doing dozens of calls to discover API groups twice - firstly when setting up informers, and next, when executing `kubectl` commands (when it is enabled in settings).
Currently, the cachedDiscoveryClient is in-memory based. I converted it to disk-based one, using the same path for cache as `kubectl`: https://github.com/pkosiec/botkube/compare/fix-kubectl-cache-write...pkosiec:share-kubectl-cache?expand=1
However, I'm not really sure if that brings any significant value - digging deeper, both clients read/write the same cache even if they weren't created by a given client …
=> Fix writing cache for kubectl exec commands

pkg/events/events.go
This PR fixes the bug where BotKube is crashing while building events.
Add a condition to check the event.Series object is nil before accessing its field.
=> Set event TimeStamp if K8s event Series is not nil

pkg/bot/export_test.go, pkg/bot/slack.go, pkg/bot/slack_test.go
- Do not log full Slack event details in case of unmarshalling error
This is an issue of the upstream library. While I prepared a workaround, I also prepared a simple change in `slack-go/slack` repo: https://github.com/slack-go/slack/pull/1067
**NOTE:** This pull request depends on #582. Please merge #582 first, and I will rebase this one.
Actual changes on this PR: https://github.com/infracloudio/botkube/commit/7813821947c6cbcc7d7040f3fb1a70ed57e9a4f6
Fixes #579
See the original issue for testing instruction: #579
You can use `pkosiec/botkube:slack-unmarshall-err` Docker image for testing the workaround.
Once you run my image and try to reproduce the issue, you'll see in the logs:
```
ERRO[2022-05-19T16:00:57Z] Slack unmarshalling error: RTM Error: Received …
```
=> Do not log full Slack event details in case of unmarshalling error

helm/botkube/templates/_helpers.tpl, helm/botkube/templates/deployment.yaml, helm/botkube/templates/sslcert.yaml, helm/botkube/values.yaml
- Documentation Pull Request
- Add option to specify external secret with SSL cert
- Document Secret format for `kubeconfig`, `ssl`, and `communication` settings.
Related issue: https://github.com/infracloudio/botkube/issues/480
An  option to specify external secret with SSL cert can be tested with `helm template`:
1. Checkout this PR: `gh pr checkout 597`
2. Run with external Secret:
```bash
helm template ./helm/botkube/ --namespace botkube --set config.ssl.enabled=true --set config.ssl.existingSecretName=external-ssl-cert
```
See that there is only **one** Secret for communication, and for certs the `external-ssl-cert` name is used.
4. Run with auto created secret:
```bash
helm template ./helm/botkube/ --namespace botkube --set config.ssl.enabled=true --set …
```
=> Add and describe opt to specify sensitive data via external secrets

helm/botkube/templates/servicemonitor.yaml
- Fix ServiceMonitor selector
Fixes #431 
Install Prometheus stack with BotKube.
```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install monitoring prometheus-community/kube-prometheus-stack
cat > /tmp/values.yaml << ENDOFFILE
config:
settings:
clustername: sample
kubectl:
enabled: true
serviceMonitor:
enabled: true
labels:
release: monitoring
ENDOFFILE
helm install botkube ./helm/botkube -f /tmp/values.yaml --wait
kubectl port-forward svc/monitoring-kube-prometheus-prometheus 9090:9090
```
See targets on http://localhost:9090/targets page. BotKube target will be up after a while.
=> Fix ServiceMonitor selector

.github/workflows/pr-image.yaml, .goreleaser.yml, Makefile, hack/goreleaser.sh
Add an option to push the BotKube image automatically on PR. It's alternative approach for https://github.com/infracloudio/botkube/pull/604.
This PR will solve the problem with manual PR builds, e.g. we had that issue here:
- https://github.com/infracloudio/botkube/pull/601
- https://github.com/infracloudio/botkube/pull/593
- https://github.com/infracloudio/botkube/pull/582
- https://github.com/infracloudio/botkube/pull/583
Example run: https://github.com/mszostok/botkube/runs/6714112689?check_suite_focus=true
Fixes #590 
To ensure that secrets won't be available for untrusted code, first we need to build the image and share it with the second job, which doesn't check out the untrusted code and can safely push an artifact to ghcr.io.
The flow is as follows:
``` …
```
=> Add option to build&push image on PR automatically

.golangci.yml, Makefile, go.mod, go.sum, helm/botkube/values.yaml, pkg/execute/executor.go, pkg/execute/executor_test.go, pkg/filterengine/filterengine.go, pkg/filterengine/filters/ingress_validator.go, pkg/filterengine/filters/ingress_validator_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test.Dockerfile, test/doc.go, tests/README.md, tests/e2e/k8s_helpers_test.go, tests/e2e/slack_test.go, tests/e2e/slack_tester_test.go
- Implement E2E tests against BotKube deployed on K8s and real Slack API
- Allow building Docker image
- Ensure output from FilterEngine and Executor are predictable (same order every map iteration)
- Change missing TLS secret from Recommendation to Warning
- Add happy path unit test for Ingress validation filter (to make sure we will be able to remove current E2E tests with fake Slack and K8s in near future as the coverage is equal or higher)
This PR will be followed-up by a dedicated PR which run these tests on CI (with `helm test`).
See https://github.com/infracloudio/botkube/issues/615
1. Check out this PR
1. See the testing instruction in the `./tests` package.
=> Implement E2E tests against BotKube deployed on K8s and real Slack API

.github/workflows/branch-build.yml, .github/workflows/ci.yml, .github/workflows/pr-build.yaml
- Get Go version from the go.mod file on CI
I found out that there is a nice feature that we can use https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file. As a result, we have a single source of truth about used Go version. As we don't test our code with multiple version (matrix) it's IMO a great solution.
=> Get Go version from the go.mod file on CI

helm/botkube/e2e-test-values.yaml, pkg/execute/executor.go, pkg/execute/executor_test.go, pkg/execute/factory.go, pkg/execute/kubectl/merger.go
- Return executors enabled only in a given channel. Previously, all enabled executors were displayed, even if a given channel didn't have suitable bindings for it.
Fix https://github.com/kubeshop/botkube/issues/668
=> Return executors enabled only in a given channel

helm/botkube/e2e-test-values.yaml, pkg/config/config.go, pkg/controller/controller.go, pkg/events/events.go, pkg/ptr/ptr.go, pkg/recommendation/export_test.go, pkg/recommendation/factory.go, pkg/recommendation/factory_test.go, pkg/recommendation/resource_events.go, pkg/recommendation/resource_events_test.go, pkg/sources/sources.go, pkg/sources/sources_test.go
-  Handle recommendations even if no such resources are configured for notifications
Now the recommendations are passed to all configured
**NOTE:** The recommendations don't have configurable namespaces. If they are enabled, BotKube notifies about Pod/Ingress resources from all namespaces if they contain any warning/recommendation.
The changes has been tested in E2E tests as well as unit ones.
You can use sample config:
```yaml
sources:
'k8s-events':
kubernetes:
recommendations:
pod:
noLatestImageTag: true
labelsSet: true
ingress:
backendServiceValid: true
tlsSecretValid: true
resources: []
'k8s-events2':
kubernetes:
recommendations:
pod:
noLatestImageTag: true
labelsSet: true
ingress:
backendServiceValid: true
tlsSecretValid: true
resources:
- name: …
```
=>  Handle recommendations even if no such resources are configured for notifications

pkg/events/events.go
- Ignore resource object when marshalling event to JSON
During 0.13 RC1 testing @ezodude found an issue with sending events to Elasticsearch. This PR fixes the issue.
Elasticsearch sink has the following line of code:
```go
_, err = e.client.Index().Index(indexName).Type(indexCfg.Type).BodyJson(event).Do(ctx)
```
So we need to make sure the resource object is ignored.
=> Ignore resource object when marshalling event to JSON

cmd/botkube/main.go, pkg/execute/default_runner.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/kubectl.go, pkg/execute/kubectl_test.go
Previously the deprecated `--short` flag was used to get the k8s version. 
- Use the `json` format to get the k8s version
1. Create cluster
```bash
k3d cluster create labs --image rancher/k3s:v1.24.4-k3s1
```
2. Install `botkube`
```bash
export SLACK_BOT_TOKEN="xoxb-" # WARNING: It is token for BotKube Slack bot, not the Tester!
helm upgrade botkube --namespace botkube --install --create-namespace \
--set communications.default-group.slack.enabled=true \
--set communications.default-group.slack.channels.default.name=random \
--set communications.default-group.slack.token="${SLACK_BOT_TOKEN}" \
--set settings.clusterName=slack \
--set executors.kubectl-read-only.kubectl.enabled=true \
--set image.repository=kubeshop/pr/botkube \
--set image.tag=706-PR …
```
=> Make more robust getting the k8s version

hack/goreleaser.sh
- Fix build single image target
As @madebyrogal noticed, our [contribution guide](https://github.com/kubeshop/botkube/blob/main/CONTRIBUTING.md#build-and-install-on-kubernetes) says:
``````
```sh
IMAGE_PLATFORM=linux/arm64 make container-image-single
docker tag ghcr.io/kubeshop/botkube:v9.99.9-dev <your_account>/botkube:v9.99.9-dev
docker push <your_account>/botkube:v9.99.9-dev
```
``````
And our `container-image-single` target produces `kubeshop/botkube:v9.99.9-dev` image. This PR fixes it.
=> Use image registry when building single Docker image

test/e2e/bots_test.go
- Disable Discord E2E tests temporarily
This test currently keeps failing on CI. Skipping it temporarily to unblock the team until it's fixed.
NOTE: Didn't want to skip it on GH actions level to make sure they can be easily fixed in a follow-up PR and the Ci pipeline will verify if the fix works.
https://github.com/kubeshop/botkube/issues/307
CC @ezodude
=> Disable Discord E2E tests temporarily

cmd/botkube/main.go, helm/botkube/README.md, helm/botkube/templates/botkube-cm.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/templates/systemroles.yaml, helm/botkube/values.yaml, internal/storage/help.go, pkg/config/config.go, pkg/config/default.yaml, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/execute/notifier_test.go, pkg/sources/sources.go
- Persist sent help messages
I wanted to add the e2e tests but I would impact the future improvements with parallel test. I cannot modify the BotKube configuration and delete the pod. 
Manual testing:
1. Checkout this branch: `gh pr checkout 738`
2. Create cluster: `k3d cluster create`
3. Install BotKube with Slack:
```yaml
default-group:
slack:
channels:
default:
name: random
enabled: true
appToken: "xapp-1-"
botToken: "xoxb-"
image:
repository: kubeshop/pr/botkube
pullPolicy: Always
tag: 738-PR
analytics:
disable: true
```
```
helm upgrade botkube --install --namespace botkube ./helm/botkube --create-namespace -f /tmp/slack.yaml
```
4. See the help message on the #random channel.
5. Delete the Pod (simulate restart): `kubectl -n …
=> Persist sent help messages

helm/botkube/README.md, helm/botkube/e2e-test-values.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/recommendation/resource_events.go, pkg/sources/sources.go, pkg/sources/sources_test.go
- Add option to set events list globally
- Define different k8s source presets
- `k8s-recommendation-events` - enables all possible k8s recommendations
- `k8s-all-events` - is the name of the previous configuration
- `k8s-err-events` - enables only `error` events for resources that were watched previously
- #710
=> Define different k8s source presets, add option to set event list globally

helm/botkube/templates/persistent-config.yaml
- Merge persistent config ConfigMaps between Helm upgrades
Checkout this PR and export the following envs:
```bash
export WS_SLACK_BOT_TOKEN=""
export WS_SLACK_APP_TOKEN=""
```
Install BotKube:
```bash
cat > /tmp/values.yaml << ENDOFFILE
'default-group':
socketSlack:
enabled: true
botToken: "${WS_SLACK_BOT_TOKEN}"
appToken: "${WS_SLACK_APP_TOKEN}"
channels:
'default':
name: botkube-test
notification:
disabled: true
bindings:
executors:
- kubectl-read-only
sources:
- k8s-events
'second':
name: botkube-demo
bindings:
executors:
- kubectl-read-only
sources:
- k8s-events
settings:
clusterName: dev
executors:
'kubectl-read-only':
kubectl:
enabled: true
analytics:
disable: true
image:
repository: kubeshop/pr/botkube
tag: '762-PR' …
```
=> Merge persistent config ConfigMaps between Helm upgrades

pkg/execute/executor.go, pkg/execute/kubectl.go, pkg/execute/kubectl_test.go, test/e2e/bots_test.go
- Support kubectl commands both on root and with prefix, e.g. `@BotKube get po` and `@BotKube kubectl get po`
- Possible aliasses: `kubectl`, `kc`, `k`
#728
https://github.com/kubeshop/botkube-docs/pull/150
Run combination of commands:
- `@BotKube get pods`
- `@BotKube kubectl get pods`
- `@BotKube kc get pods`
- `@BotKube k get pods`
=> Support kubectl aliases

internal/analytics/noop_reporter.go, internal/analytics/reporter.go, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportCommand.json, pkg/bot/slack_renderer.go, pkg/bot/socketslack.go, pkg/execute/edit.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/helper_test.go, pkg/execute/notifier.go
- Add analytics to slack interactive buttons. IMO that's the simplest implementation.
I tried to not modify the code where the `ReportCommand` was used and instead pass func there (see: [bd5020d](https://github.com/kubeshop/botkube/pull/770/commits/bd5020da642d7f55afea53c07e918518ed7470b8#diff-6fe247c9584512f88190e551aeeb30dfedf84d5a4de4aa0a35a9ab1ec221b32aR116-R119)) but the problematic part is for instances such as notifier or edit manager where we already pass the `analyticsReporter`. In this case, to avoid reaces we would need to always do `NewEditExecutor`,`NewNotifierExecutor`, each time we construct executor. IMO this is not worth it. 
We don't need to update our privacy policy as we still only work in "command" area.
To test that you need to …
=> Add analytics to slack interactive buttons

test/e2e/bots_test.go, test/e2e/bots_tester_test.go, test/e2e/discord_driver_test.go, test/e2e/slack_driver_test.go
Added tests color schema for message attachment (embeded) in Slack & Discord
fix https://github.com/kubeshop/botkube/issues/730
Run integration tests (it was added for attachment assertion)
=> Use color scheme in E2E tests

pkg/bot/interactive/message.go, pkg/bot/slack.go, pkg/bot/slack_renderer.go, pkg/bot/socketslack.go, pkg/execute/executor.go
- Introduced "Filter Output" feature to message responses that has > 16 lines
- Supports both markdown responses and file uploads due to slack message size limit.
- Checkout BotKube to your local computer
```bash
gh pr checkout 805 --repo=https://github.com/kubeshop/botkube
```
- Prepare `comm_config.yaml` with containing slack credentials as follows
<details>
<summary>Show</summary>
```yaml
'default-group':
socketSlack:
enabled: true
appToken: "xapp-1..."
botToken: "xoxb-..."
notification:
type: "long"
channels:
'default':
name: botkube-demo
bindings:
executors:
- kubectl-backend
sources:
- k8s-all-events
- k8s-recommendation-events
settings:
clusterName: gke-playground
configWatcher: true
lifecycleServer:
deployment:
name: botkube …
```
=> Interactive output filtering

internal/analytics/noop_reporter.go, internal/analytics/reporter.go, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportCommand.json, pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/bot/socketslack.go, pkg/bot/teams.go, pkg/execute/command/origin.go, pkg/execute/edit.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/fake_kc_guard.go, pkg/execute/helper_test.go, pkg/execute/kubectl/guard.go, pkg/execute/kubectl_cmd_builder.go, pkg/execute/notifier.go
- Filter not supported verbs for interactive kubectl (currently it is not used, but @mszostok will switch to actual Command Guard in one of the next PRs)
- Implement telemetry for actionable messages
- Add missing telemetry to `help` and `feedback` typed commands
- Fix "invalid verb" problem for the `edit` command, even if the verb is valid
To test against real Segment, contact me 🙂  Alternatively, you can test it with fake reporter with the following instruction:
Check out this PR.
Replace noop_reporter.go `ReportCommand` method with:
```go
// ReportCommand reports a new executed command. The command should be anonymized before using this method.
func (n NoopReporter) ReportCommand(a config.CommPlatformIntegration, b string, c command.Origin) error …
```
=> Filter not supported verbs by interactive `kubectl`, improve telemetry for interactive Slack messages

pkg/bot/interactive/message.go, pkg/bot/slack.go, pkg/bot/slack_renderer.go, pkg/bot/socketslack.go, pkg/execute/executor.go, pkg/execute/kubectl_cmd_builder.go, pkg/execute/kubectl_cmd_builder_msg.go, pkg/execute/kubectl_cmd_builder_test.go
- Add opt to append filter when building the `kubectl` command
- Reduce the Slack message size
https://user-images.githubusercontent.com/17568639/195589745-aa441d0c-ce97-4278-8ac3-03b6559ebd5b.mov
#748
=> Add opt to append filter when building the `kubectl` command

go.mod, test/e2e/bots_test.go, test/e2e/bots_tester_test.go, test/e2e/diff_helpers_test.go, test/e2e/discord_driver_test.go, test/e2e/k8s_helpers_test.go, test/e2e/slack_driver_test.go
The return type of function MessageAssertion is updated from `bool` to `(bool, int, string)`.
Other corresponding changes are made base on this change. 
- The returned `int` value indicates the number of matched blocks between expect message and actual got message.
- The returned `string` value is the diff between expect message and actual got message.
This PR compares number of matched blocks and print the diff corresponding to the maximum
value of number of matched blocks.
Resolves: #772
=> Print diff between expected and actual messages in e2e tests

cmd/botkube/main.go, pkg/execute/factory.go, pkg/execute/fake_kc_guard_test.go, pkg/execute/kubectl/guard.go, pkg/execute/kubectl/guard_test.go, pkg/execute/kubectl_cmd_builder.go, pkg/execute/kubectl_cmd_builder_msg.go, pkg/execute/kubectl_cmd_builder_test.go
- Use real command guard 
- Use cached K8s client - otherwise the interactive kc builder doesn't work as we are throttled by the K8s and we cannot return the response within 3 sec which is a req from Slack server,
- Fix bug with orphan resource name, see https://user-images.githubusercontent.com/7155799/195316607-3a55f1a3-8d0a-4b0f-9299-e5420c26593a.mp4
- In case of dropdown error, just don't print them
- In case of rendering the command preview, return:
#748
=> Use real command guard and cached client, fix bug with orphan resource name

CONTRIBUTING.md, test/README.md
- Updated Botkube helm installation instructions for contributors.
- Linked to docs as reference installation instructions when encountering problems.
- Added a new step to ensure a Slack integration is already setup.
- General tidy up.
Resolves #804
=> The CONTRIBUTING.md file is outdated

pkg/execute/kubectl_cmd_builder.go, pkg/execute/kubectl_cmd_builder_msg.go, pkg/execute/kubectl_cmd_builder_test.go
This PR address the Lacho feedback for the current implementation:
- Add namespace label to the `default` keyword (ONLY to it, rest should be without it):
- Change filter placeholder
#748
=> Add namespace label to default keyword, change filter placeholder

CONTRIBUTING.md, comm_config.yaml.tpl, global_config.yaml.tpl, helm/botkube/Chart.yaml, helm/botkube/README.md, helm/botkube/README.tpl.md, helm/botkube/values.yaml, pkg/execute/kubectl/commander.go, pkg/execute/kubectl/commander_test.go
- Prevent resource deletion from the actionable notifications
- This is the minimal acceptable option to avoid accidental resource deletion. As this is a rare edge case, it will be followed-up according to the community demand in https://github.com/kubeshop/botkube/issues/824.
- Unify documentation placeholder style (use `{ }` instead of `< >`
- Fix Helm chart icon and set Helm chart version on main to dev
- The release pipeline will change it anyway, but at least it won't look odd on `main` that we have an outdated `0.13` chart. 
Follow the same instructions from https://github.com/kubeshop/botkube/pull/803.
You won't see the `delete` option for any event notification anymore.
Resolves https://github.com/kubeshop/botkube/issues/786
=> Prevent resource deletion from the actionable notifications

pkg/execute/kubectl/guard.go, pkg/execute/kubectl/guard_test.go, pkg/execute/kubectl/resource-normalizer.go
- Work around empty K8s resources list which causes Botkube crash
See the discussion under #829.
DO NOT checkout this PR (yet)
1. Install [KEDA](https://github.com/kedacore/charts/tree/main/keda) (Helm chart).
1. Run Botkube locally
```bash
export BOTKUBE_SETTINGS_LOG_LEVEL=info
export BOTKUBE_SETTINGS_KUBECONFIG=$KUBECONFIG
export BOTKUBE_CONFIG_PATHS="$(pwd)/resource_config.yaml,$(pwd)/comm_config.yaml"
go run ./cmd/botkube/main.go
```
1. See the crash error
1. Check out to this PR with `gh pr checkout 834`
1. Run Botkube locally once again
Resolves #829
=> Work around empty K8s resources list which causes Botkube crash

pkg/bot/interactive/help.go, pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt, pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt, pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
- Added e.g. to clarify the warning example
- Added description to the interactive kubectl section for the socket Slack help to differentiate interactive kubectl builder from typed kubectl commands
=> Fixup `kubectl` help wording

test/e2e/bots_test.go
- Move actions list E2E test after initial help message
The E2E tests are flaky as bot didn't respond - we should wait for Bot initial message before running any command.
This PR will have the tests rerun 3 times to make sure everything works as expected:
- https://github.com/kubeshop/botkube/actions/runs/3546594270/attempts/1
- https://github.com/kubeshop/botkube/actions/runs/3546594270
- https://github.com/kubeshop/botkube/actions/runs/3546594305
#833
=> Move actions list E2E test after initial help message

.github/workflows/branch-build.yml, .github/workflows/pr-build.yaml
- Currently, when one of a job in matrix fails, the other one is canceled. This is problematic when we want to debug the root cause of the failure. If we make those jobs independent then we can see which one really fails and if it is a generic problem or only with one of our platform integration.
Changes are introduced based on the GitHub action documentation: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
Example where Discord test failed and as a result canceled the Slack testing: https://github.com/kubeshop/botkube/actions/runs/3677219708
=> Make the integration jobs independent

.github/workflows/branch-build.yml, .github/workflows/pr-build.yaml, .github/workflows/release.yml, .gitignore, .goreleaser.plugin.yaml, .goreleaser.yml, Makefile, hack/gen-plugin-index.go, helm/botkube/e2e-test-values.yaml, test/README.md, test/helpers/plugin_server.go
https://youtu.be/b06cZRzlJgM
Merge after: https://github.com/kubeshop/botkube/pull/884
**Flow:**
1. Plugins binaries are build via GoReleaser
- the `version` field is automatically set via ldflags
- binary name format: `{executor|source}_{pluginName}_{os}_{arch}`
2. The index file is built via Go service based on directory with plugins binaries
- type, plugin name, os and arch parameters are parsed from the binary name
- description and version are taken by calling the `Metadata` method on each plugin
Benefits of implemented approach with auto-generation:
- because we use the Go code, we use always up-to-date index entry definition. If we change/add a property, it will be automatically reflected in the generated index file
- the e2e tests and release …
=> Add release process for Botkube plugins

pkg/execute/action.go, pkg/execute/command.go, pkg/execute/config.go, pkg/execute/default_runner.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/feedback.go, pkg/execute/filter.go, pkg/execute/help.go, pkg/execute/mapping.go, pkg/execute/notifier.go, pkg/execute/notifier_test.go, pkg/execute/ping.go, pkg/execute/sourcebinding.go, pkg/execute/version.go, test/e2e/bots_test.go, test/e2e/discord_driver_test.go
For commands that support subcommands/resources, when such subcommand is missing, return a dynamically
generated table of all subcommands supported by the command.
#703
=> Dynamically generate help messages

internal/plugin/logger.go, pkg/config/config_test.go, pkg/config/plugin.go, pkg/config/plugin_test.go
- Make plugin logger independent - currently changing the plugin level also change the Botkube one, and otherwise.
- Fix naming in err msgs
=> Make plugin logger independent, fix naming in err msgs

.golangci.yml, cmd/executor/echo/main.go, pkg/execute/executor.go, pkg/execute/kubectl.go, pkg/execute/params.go, pkg/execute/plugin_executor.go, test/e2e/bots_test.go, test/e2e/discord_driver_test.go
- Once the `@Botkube list --help` was specified the Botkube panic, as it was not handled properly by filter executor
- don't use filtering twice (now it's used only in `respond` function)
- fix logged field in plugin executor
- ignore `--help,-h` flag in exec filter
- handle `ExecutionCommandError` in plugin response (e2e tested via `@Botkube echo @fail`)
=> Fix bugs in executors

test/e2e/bots_test.go, test/e2e/discord_driver_test.go
- Add option to set discord user's ID directly
=> Add option to set discord user's ID directly

pkg/execute/config.go, pkg/execute/config_test.go, pkg/execute/executor.go, pkg/execute/mapping.go, pkg/execute/notifier.go, pkg/execute/notifier_test.go, test/e2e/bots_test.go
Based on #703 notifier verbs are `enable, disable` and not `start, stop`.
#703
=> Fix notifier verbs

pkg/bot/interactive/help.go, pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt, pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt, pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt, pkg/execute/kubectl.go, pkg/execute/kubectl_test.go, test/e2e/bots_test.go
- Replace removed 'list commands'
- Print multi-cluster info only for supported platforms
Here is the updated Slack help message:
Fix https://github.com/kubeshop/botkube/issues/891
=> Replace removed 'list commands', print multi-cluster info only for supported platforms

pkg/bot/discord.go, pkg/bot/interactive/help.go, pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt, pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt, pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt, pkg/execute/executor.go, pkg/execute/kubectl.go, pkg/execute/kubectl/checker.go, pkg/execute/kubectl/merger.go, pkg/execute/kubectl_test.go, test/e2e/bots_test.go
- Remove support for running kubectl command without prefix
Related doc change: https://github.com/kubeshop/botkube-docs/pull/190
Fix https://github.com/kubeshop/botkube/issues/802
=> Remove support for running kubectl command without prefix

cmd/botkube/main.go, helm/botkube/README.md, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml, pkg/config/config.go, pkg/config/config_test.go, pkg/config/default.yaml, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/execute/config_test.go
New http server is started with two handlers: ready and live. Both endpoints right now always return `200 ok`.
https://github.com/kubeshop/botkube/issues/881
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#interpreted_hc
=> Add health endpoints

pkg/execute/sourcebinding.go
- Print `DISPLAY NAME` column for command `@botkube status sourcebindings`
=> Print Display Name for `status sourcebindings`

internal/executor/helm/executor.go, internal/executor/helm/executor_test.go, internal/executor/helm/help.go
- Add default helm namespace. By default, (when `-n/--namespace` is not provided) the Helm CLI used the namespace where Botkube was deployed and not the `default` one. 
- Update `helm help`
1. Global Help
```bash
@Botkube helm help
@Botkube helm --help
```
1. Install (default and test namespace)
```bash
@Botkube helm install -h
@Botkube helm install
--repo https://charts.bitnami.com/bitnami psql postgresql
--set clusterDomain='testing.local'
@Botkube helm install https://charts.bitnami.com/bitnami/postgresql-12.1.0.tgz --create-namespace -n test --generate-name
```
1. List (default and all namespaces)
```bash
@Botkube helm list
@Botkube helm list -A
@Botkube helm list -f 'p' -A
```
1. Upgrade (default namespace)
```bash
@Botkube helm upgrade --repo …
```
=> Add default helm namespace, update helm help

pkg/event/event.go
- Fix marshalling event for Elasticsearch integration
The `ObjectMeta` shouldn't be sent to Elasticsearch. That was an issue introduced a while ago.
- Use the values:
```yaml
image:
tag: 923-PR
repository: kubeshop/pr/botkube
"default-group":
elasticsearch:
enabled: true
server: http://elasticsearch-master.default:9200
username: elastic
password: changeme
skipTLSVerify: false                      # toggle verification of TLS certificate of the Elastic nodes. Verification is skipped when option is true. Enable to connect to clusters with self-signed certs
indices:
'default':
bindings:
sources:
- k8s-err-events
- k8s-recommendation-events          
- k8s-create-events
actions:
'describe-created-resource':
enabled: true …
```
=> Fix marshalling event for Elasticsearch integration

.github/workflows/release.yml
- Fix changelog generation
Local run:
```
gh api repos/kubeshop/botkube/releases/generate-notes \
-f tag_name="v0.17.0" \
-f previous_tag_name="v0.16.0" \
-q .body > CHANGELOG.md
```
generates a valid changelog. When the `previous_tag_name` is not specified, the `auto` is used, and it doesn't work well in our scenario.
=> Fix changelog generation

cmd/botkube/main.go, helm/botkube/README.md, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml, internal/config/gql_provider.go, internal/config/gql_provider_test.go, pkg/config/config.go
- `config.provider.endpoint` helm option is added
- `config.provider.identifier` helm option is added
```bash
helm install --version v0.17.0 botkube --namespace botkube --create-namespace \
--set settings.clusterName=dev \
--set executors.kubectl-read-only.kubectl.enabled=true \
--set 'executors.helm.botkube/helm.enabled'=false \
--set config.provider.identifier=12123 \
--set config.provider.endpoint=http://localhost:8080/graphql \
./helm/botkube
```
```bash
helm install --version v0.17.0 botkube --namespace botkube --create-namespace \
--set settings.clusterName=dev \
--set executors.kubectl-read-only.kubectl.enabled=true \
--set 'executors.helm.botkube/helm.enabled'=false \
./helm/botkube
```
Resolves #931
=> helm option is added for config source

internal/plugin/manager.go, internal/plugin/manager_test.go, internal/source/dispatcher.go, pkg/bot/interactive/help.go, pkg/config/config.go, pkg/format/title.go
- Fetch only used plugin repositories, 
- Fix logging messages, 
- Add repo validation, so user gets more useful error message
-  without that you only get `not found source plugin called "cm-test" in "botkube" repository`.  And it's misleading as it suggests that the `botkube` repository was found. Now, as the repositories are validated, this error message is valid.
Fix #939
=> Fetch only used plugin repositories, fix logging, add repo validation

.github/workflows/branch-build.yml, .github/workflows/pr-build.yaml, .github/workflows/upload-plugins.yaml
- Github action that builds and uploads plugins to GCP
Resolves #943
=> Upload plugins to GCS

.github/workflows/pr-build.yaml, internal/source/prometheus/source.go, pkg/api/executor/executor.pb.go, pkg/api/source/source.pb.go
- Fix Prometheus source JSON schema
- Fix `check-generated-resources` job. Changes will be applied after merge.
Checkout this PR and run:
```bash
PLUGIN_DOWNLOAD_URL_BASE_PATH="http://localhost:8080/plugin-dist" make gen-plugins-index
```
Then verify the output index file to see if the schema is valid. You can use https://www.jsonschemavalidator.net/ to validate both previous and current (from this PR) schemas.
=> Fix Prometheus source JSON schema and generated resources CI job

.goreleaser.plugin.yaml, cmd/executor/gh/main.go
- Add GitHub issue creator
Code moved from: https://github.com/kubeshop/botkube-plugins-template/pull/7
Here is a release made on my own repo created from this template:
https://github.com/mszostok/botkube-plugins/releases/tag/v1.1.0
```bash
export SLACK_CHANNEL_NAME={channel_name}
export SLACK_APP_TOKEN={token}
export SLACK_BOT_TOKEN={token}
export PLUGINS_URL="https://github.com/mszostok/botkube-plugins/releases/download/v1.1.0/plugins-index.yaml"
export REPOSITORY={repo} # format OWNER/REPO_NAME, e.g. kubeshop/botkube
export GITHUB_TOKEN={token}
helm install --version v0.17.0 botkube --namespace botkube --create-namespace \
--set communications.default-group.socketSlack.enabled=true \
--set …
```
=> Add GitHub issue creator

comm_config.yaml.tpl, helm/botkube/README.md, helm/botkube/values.yaml, pkg/config/config.go
- Comment deprecated Slack properties in Helm chart and code
While we still use deprecated Slack integration for tests (until #865 is done), we should explicitly mention to avoid using the deprecated property. This PR adds proper comments to encourage switching to the new integration.
See also https://github.com/kubeshop/botkube/issues/865
=> Comment deprecated Slack configuration properties

cmd/botkube/main.go, helm/botkube/e2e-test-values.yaml, pkg/config/config.go, pkg/config/config_test.go, pkg/config/testdata/TestLoadedConfigValidationErrors/invalid-alias-command.yaml, pkg/config/testdata/TestLoadedConfigValidationErrors/missing-alias-command.yaml, pkg/config/validator.go, pkg/execute/action.go, pkg/execute/alias.go, pkg/execute/alias/list.go, pkg/execute/alias/list_test.go, pkg/execute/alias_test.go, pkg/execute/command/verb.go, pkg/execute/config.go, pkg/execute/exec.go, pkg/execute/executor.go, pkg/execute/feedback.go, pkg/execute/filter.go, pkg/execute/help.go, pkg/execute/mapping.go, pkg/execute/notifier.go, pkg/execute/ping.go, pkg/execute/source.go, pkg/execute/sourcebinding.go, pkg/execute/version.go, test/e2e/bots_test.go
- Validate alias command prefixes
- Display builtin command aliases
- Use proper context for querying Botkube config from GraphQL and editing SourceBindings
No need to test it manually as the functionality was covered by unit and integration tests.
Resolves https://github.com/kubeshop/botkube/issues/870
Resolves https://github.com/kubeshop/botkube/issues/908
=> Validate alias commands and display builtin command aliases

internal/source/prometheus/source.go
- Update prometheus message format
=> Update prometheus message format

pkg/execute/action.go, pkg/execute/alias.go, pkg/execute/config.go, pkg/execute/config_test.go, pkg/execute/exec.go, pkg/execute/exec_test.go, pkg/execute/executor.go, pkg/execute/executor_filter.go, pkg/execute/executor_filter_test.go, pkg/execute/filter.go, pkg/execute/mapping.go, pkg/execute/source.go, pkg/execute/sourcebinding.go
- Add SourceBindings alias (`sb`)
- Fix executing filtering for each command even if `--filter` is not passed
- Filter reporting of filtered command
- Don't report invalid feature for command without provided one
Checkout the PR and run Botkube locally with any config.
Edit `noop_reporter.go` and change `ReportCommand`
```go
// ReportCommand reports a new executed command. The command should be anonymized before using this method.
func (n NoopReporter) ReportCommand(plat config.CommPlatformIntegration, cmd string, org command.Origin, filtered bool) error {
// print all input params to make sure they are passed correctly
log.Println("ReportCommand", plat, cmd, org, filtered)
return nil
}
```
Run `@Botkube edit` and see `sb` alias available.
See that …
=> Add SourceBindings built-in alias and fix filtering commands

global_config.yaml.tpl, go.mod, go.sum, helm/botkube/README.md, helm/botkube/values.yaml, internal/source/registration.go, internal/source/registration_test.go, internal/source/router.go, internal/source/router_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/config/testdata/TestLoadConfigWithPlugins/config-all.yaml, pkg/config/testdata/TestLoadedConfigValidationWarnings/executors-include-warning.yaml, pkg/config/validator.go, pkg/execute/kubectl/merger.go, pkg/execute/kubectl/merger_test.go, pkg/execute/kubectl_cmd_builder.go, pkg/execute/kubectl_cmd_builder_test.go, pkg/execute/kubectl_test.go, pkg/recommendation/resource_events_test.go
- Support `include/exclude` regexes for `event.reason`, `event.message` and `resources[].name`.
_(To copy and paste in https://github.com/kubeshop/botkube/issues/972)_
- Kubernetes source constraints `event.reason`, `event.message` and `resources[].name` are now objects with two lists: `include` and `exclude`. Both take exact values or regex patterns. Exclude takes precedence over include.
This allows you to set `exclude` patterns, and also unifies the configuration with `namespaces` constraints.
I didn't rename `namespaces` to `namespace` or `event.types` to `event.type` as I weren't sure if that's a good change. However, if you have any ideas, then please let me know - we're already doing a breaking change here, so I can unify the config properties …
=> Support include/exclude regexes for event and resource constraints

cmd/botkube/main.go, helm/botkube/README.md, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml, internal/config/env_provider.go, internal/config/gql_client.go, internal/config/gql_client_test.go, internal/config/gql_provider.go, internal/config/gql_provider_test.go, pkg/config/config.go, pkg/config/config_test.go
- Include API Key when fetching remote Botkube configuration
On your Kubernetes cluster:
Install echo server:
```bash
helm repo add ealenn https://ealenn.github.io/charts
helm repo update ealenn
helm install echo-server ealenn/echo-server --set application.logs.ignore.ping=true --set application.enable.environment=false --wait
```
Checkout PR and install botkube:
```bash
gh pr checkout 980
helm install botkube -n botkube --create-namespace \
--set image.repository=kubeshop/pr/botkube \
--set image.tag=980-PR --set config.provider.endpoint="http://echo-server.default" --set config.provider.identifier="123" --set config.provider.apiKey="my-api-key" ./helm/botkube
```
See the logs of echo server 🙂 
```
k logs echo-server-d54559dfc-z6x8j
(node:1) …
```
=> Include API Key when fetching remote Botkube configuration

cmd/botkube/main.go, internal/config/gql_client.go, internal/config/gql_client_test.go, internal/config/gql_provider.go, internal/config/gql_provider_test.go, internal/graphql/client.go, internal/status/gql_reporter.go, internal/status/noop_reporter.go, internal/status/reporter.go, pkg/config/config.go, pkg/config/config_test.go, pkg/controller/controller.go
- Report botkube status to the backend
Deploy backend locally:
```shell
docker run -d -p 5432:5432 --name botkube -e POSTGRES_PASSWORD=s3cr3t -d postgres
cp config.dist.yaml config.yaml`
CONFIG_LOCATION=./config.yaml go run server.go
```
Visit http://localhost:8080
```graphql
mutation{
createDeployment(input: {
name: "cls1",
plugins: [
{
groups: [
{
name: "kubernetes-info",
displayName: "kubernetes-info"
type: SOURCE,
configurations: [
{
name: "kubernetes",
configuration: "{\"recommendations\":{\"pod\":{\"noLatestImageTag\":true,\"labelsSet\":true},\"ingress\":{\"backendServiceValid\":true,\"tlsSecretValid\":true}}}"
}
]
}
]
}
],
platforms:
{
slacks: {
name:"secondslack",
token:"apptoken"
notificationType:"short"
channels: [
{
name: "default" …
```
=> Report botkube status

cmd/botkube/main.go, internal/audit/gql_reporter.go, internal/audit/noop_reporter.go, internal/audit/reporter.go, internal/source/dispatcher.go, pkg/execute/action.go, pkg/execute/alias.go, pkg/execute/alias_test.go, pkg/execute/config.go, pkg/execute/config_test.go, pkg/execute/exec.go, pkg/execute/exec_test.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/feedback.go, pkg/execute/filter.go, pkg/execute/help.go, pkg/execute/helper_test.go, pkg/execute/notifier.go, pkg/execute/notifier_test.go, pkg/execute/ping.go, pkg/execute/source.go, pkg/execute/source_test.go, pkg/execute/sourcebinding.go, pkg/execute/sourcebinding_test.go, pkg/execute/version.go
- Report events to the backend
1. Deploy backend locally, guide [here](https://github.com/kubeshop/botkube-cloud/pull/158)
2. Create a Deployment and get API key/token
3. Use local botkube config and noop reporter by changing
```
if _, provided := os.LookupEnv(graphql.GqlProviderIdentifierEnvKey); provided {
```
to
```
if _, provided := os.LookupEnv(graphql.GqlProviderIdentifierEnvKey); !provided {
```
* [reporter.go](https://github.com/kubeshop/botkube/blob/737503971fe0b1f8023362270465f8b79eca39ea/internal/audit/reporter.go#L32)
* [config.go](https://github.com/kubeshop/botkube/blob/737503971fe0b1f8023362270465f8b79eca39ea/pkg/config/config.go#L781)
5. Add cm-watcher source:
```yaml
sources:
'cm':
displayName: "Events based on plugin" …
```
=> Report executor and source actions to backend

internal/remote/api.go, pkg/config/manager_remote.go, pkg/config/manager_remote_test.go
Add support for patching actions.
The remote call is not implemented in the backend - nothing to test.
https://github.com/kubeshop/botkube-cloud/issues/176
=> Add remote call for patching Actions

cmd/botkube/main.go, internal/analytics/segment_reporter.go, internal/audit/gql_reporter.go, internal/audit/reporter.go, internal/config/remote/gql_client.go, internal/heartbeat/gql_reporter.go, internal/remote/api.go, internal/source/dispatcher.go, internal/source/scheduler.go, internal/status/gql_reporter.go, pkg/action/provider.go, pkg/action/provider_test.go, pkg/bot/bot.go, pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/bot/socketslack.go, pkg/bot/teams.go, pkg/config/manager.go, pkg/config/manager_remote.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/mapping.go, pkg/execute/sourcebinding.go, pkg/execute/sourcebinding_test.go, pkg/ptr/ptr.go
This PR contains various bug fixes and improvements for audit reporting.
**Source event reporting:**
- Do not report audit events multiple times
- Send source display name for event reporting
**Command reporting**:
- Do not send bot platform when it is unknown (for Actions)
- Include username for command execution
- Fix channel reporting (instead of communication group, report actual channel)
- Fix plugin names reporting (e.g. `edit` for edit sourcebindings, `kubectl` for executors, `botkube/kubernetes` for sources)
**Others**
- Do not query Mattermost user + team each time a user executes a command
- Fix panics in edge cases (e.g. config endpoint not provided)
- Fix bot response when editing sourcebindings
- Fix invalid logging of deployment ID for …
=> Fix audit log reporting for source events and commands

helm/botkube/e2e-test-values.yaml, pkg/bot/slack.go, test/e2e/bots_test.go, test/e2e/bots_tester_test.go, test/e2e/discord_driver_test.go, test/e2e/slack_driver_test.go
Added e2e for RBAC for the following use cases
Fixes #945
=> RBAC e2e tests

pkg/bot/socketslack.go
- Fix reporting real name for Slack interactive events
The username was empty for audit log events when someone used interactive blocks (e.g. buttons).
=> Fix reporting real name for Slack interactive events

pkg/bot/mattermost.go
Whenever a subpath is passed on the Mattermost.URL, we should use the same path for its websocket connection string.
Fixes: https://github.com/kubeshop/botkube/issues/1037
=> Respect Mattermost websocket subpath URLs

pkg/execute/executor.go, pkg/execute/mapping.go
- Built-in commands now returns more meaningful error messages
- Run botkube with default settings
- Try built-in commands with invalid/obsolete params like `@Botkube ping test, @Botkube list non-arg`
#974
=> handle invalid commands

helm/botkube/README.md, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
- Added configurable liveness+readiness probe
```sh
helm upgrade --install botkube \
--version v1.0.0 \
--namespace botkube \
--create-namespace \
--wait \
--set config.provider.endpoint=https://api-dev.botkube.io/graphql \
--set config.provider.identifier=... \
--set config.provider.apiKey=... \
./helm/botkube
```
And check liveness + readiness probe, they should have default values as described in values.yaml. You can also customize it as shown below
```yaml
deployment:
livenessProbe:
periodSeconds: 120
readinessProbe:
periodSeconds: 120
```
```sh
helm upgrade --install botkube \
--version v1.0.0 \
--namespace botkube \
--create-namespace \
--wait \
--set config.provider.endpoint=https://api-dev.botkube.io/graphql \
--set …
```
=> configurable probes added

internal/executor/kubectl/executor.go
- Kubectl executor uses kubeconfig from exec input
- Build plugins 
- Run plugin server
- Run botkube with kubectl plugin enabled ( be aware you use local plugin server)
Relates #1021
=> use kubeconfig from exec input

cmd/executor/gh/main.go
- Now GH plugin uses kubeconfig provided by botkube core.
- Build plugins
- Run plugin serve
- Use gh plugin and run botkube
Relates #1021
=> use kubeconfig for gh plugin

helm/botkube/README.md, helm/botkube/values.yaml, pkg/action/provider.go, pkg/action/provider_test.go, pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/bot/socketslack.go, pkg/bot/teams.go, pkg/execute/executor.go, pkg/execute/factory.go
- Rename `IsAuthenticated` to `IsKnown`
- Add info logging when executing a command in not configured channel
Run Botkube locally and try to execute a command in a not configured channel. See the log.
Resolves #1059
=> Add logging when executing a command in not configured channel

cmd/executor/gh/main.go, internal/executor/helm/executor.go, internal/executor/helm/executor_test.go, internal/executor/kubectl/executor.go, internal/source/dispatcher.go, internal/source/kubernetes/source.go, pkg/api/source/grpc_adapter.go, pkg/api/source/logger.go, pkg/pluginx/kubeconfig.go
- Add validation that kubeconfig is specified
- remove the `context` property for `helm`,`kc` and `k8s` plugins
- for sources: nothing to do
- for executors: run `@Botkube helm` or `@Botkube kc`
- next, check the Botkube logs 
In the future, we should remove the internal logging and introduce an error feedback channel. Additionally, we can also consider posting errors on Slack/etc. Here we need to think whether post them directly or maybe introduce sth like `@Botkube check health` or sth similar.
Some time ago it was also mentioned here: https://github.com/kubeshop/botkube/issues/878
Fix https://github.com/kubeshop/botkube/issues/1048
=> Add validation that kubeconfig is specified

pkg/config/validator.go
- Block actions with ChannelName executors
Define a executor with `ChannelName` RBAC policy:
```yaml
executors:
k8s-default-tools:
botkube/helm:
enabled: true
config:
defaultNamespace: "default"
helmDriver: "secret"
helmConfigDir: "/tmp/helm/"
helmCacheDir: "/tmp/helm/.cache"
context: &default-plugin-context
defaultNamespace: "default"
rbac:
group:
type: ChannelName
actions:
'describe-created-resource':
enabled: true
displayName: "Describe created resource"
command: "kubectl describe {{ .Event.Kind | lower }}{{ if .Event.Namespace }} -n {{ .Event.Namespace }}{{ end }} {{ .Event.Name }}"
bindings:
sources:
- k8s-create-events
executors:
- k8s-default-tools
```
Such action config should be blocked by config validator. …
=> Block actions with ChannelName executors

.github/workflows/process-chart.yml, helm/botkube/README.md, helm/botkube/values.yaml
- Update plugin repo for release
Run the changes in isolation:
```
docker run --rm -it alpine sh
```
```bash
wget https://raw.githubusercontent.com/pkosiec/botkube/update-plugin-repo-for-release/helm/botkube/values.yaml
cat values.yaml
export LATEST_PLUGIN_INDEX_URL="https://storage.googleapis.com/botkube-plugins-latest/plugins-index.yaml"
export HELM_FOLDER="."
export NEXT_VERSION="v1.0.1"
find ${HELM_FOLDER} -name "*.yaml" -exec sed -i "s~${LATEST_PLUGIN_INDEX_URL}~https://github.com/kubeshop/botkube/releases/download/${NEXT_VERSION}/plugins-index.yaml~g" {} +
cat values.yaml
```
Resolves #1032
=> Update plugin repo for release

pkg/bot/cloudslack.go
- Auth context is added to gRPC client connections
Better to test this together with https://github.com/kubeshop/botkube-cloud/pull/431
=> gRPC client auth added

cmd/botkube/main.go, internal/executor/kubectl/builder/kubectl.go, pkg/api/message_bot_name.go, pkg/bot/cloudslack.go, pkg/execute/executor.go, pkg/execute/plugin_executor.go
-Send the cluster name for all interactive commands
The current implementation is quite hacky. The main problem is that only buttons are easily to handle as we know the whole command up front and we can simply add `--cluster-name` flag.
For all others, like selects, inputs, etc. the command is constructed either via https://github.com/kubeshop/botkube/blob/428e62405e9002a0b3b02ad9697e254521cbbb7c/pkg/bot/socketslack.go#L517-L544
or by using state https://github.com/kubeshop/botkube/blob/428e62405e9002a0b3b02ad9697e254521cbbb7c/internal/executor/kubectl/builder/kubectl.go#L393. 
This introduces additional complexity that we need to handle when we are injecting the `--cluster-name` flag as otherwise we will break the parsing on the plugin side.
I tried …
=> Send the cluster name for all interactive commands

helm/botkube/README.md, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
- Config watcher docker image is updated and now helm chart uses up to date version
- It contains fix for config watcher service token problem
=> Fix ServiceAccount token path in Config Watcher

internal/source/scheduler.go, pkg/bot/cloudslack.go, pkg/bot/socketslack.go
* Fix scheduling messages for Cloud Slack
* Remove unused command origin when sending message
(cherry picked from commit 2e9c13f32666d99265326fe2738a6d1f4b2f239a)
- Fix scheduling messages for Cloud Slack (#1108)
=> Fix scheduling messages for Cloud Slack (#1108)

internal/executor/kubectl/builder/kubectl_dropdowns.go, internal/executor/x/output/message_parser.go, pkg/api/message.go, pkg/bot/interactive/help.go, pkg/bot/interactive/plugin_help.go, pkg/bot/slack_renderer.go
- Revert API changes for api.Message
Extracted from #1122
=> Revert API changes for api.Message

cmd/executor/x/main.go, cmd/executor/x/templates/argo.yaml, cmd/executor/x/templates/flux.yaml, cmd/executor/x/templates/helm.yaml, internal/executor/x/getter/load.go, internal/executor/x/mathx/int.go, internal/executor/x/output/message_tutorial.go, internal/executor/x/run.go, internal/executor/x/run_test.go, internal/executor/x/template/config.go, internal/executor/x/testdata/TestRunnerNoExecuteTemplate/helm.yaml
- Add tutorial message template for x plugin
1. Create k3d cluster
2. Start plugin server: `env PLUGIN_SERVER_HOST=http://host.k3d.internal go run test/helpers/plugin_server.go`
3. Build x plugin: ` PLUGIN_TARGETS="x" make build-plugins`
4. Install Botkube with such example config:
<details><summary>config yaml</summary>
<p>
```yaml
default-group:
socketSlack:
enabled: true
channels:
default:
name: general
bindings:
sources: [ ]
executors:
- bins-management
appToken: "xapp-1"
botToken: "xoxb-"
executors:
bins-management:
local-repo/x:
enabled: true
context:
rbac:
group:
type: Static
static:
values: [ "system:masters" ]
config:
templates:
- ref: github.com/mszostok/botkube//cmd/executor/x/templates?ref=334eb4321e793a5d7107d000cba4a2c39d …
```
=> Add tutorial message template for x plugin

.github/workflows/branch-build.yml
- Add Slack notifications for E2E migration tests pipeline
- Add ability to trigger this pipeline via dispatch events
I thought about running also integration tests on dispatch event + getting Slack notificactions about integration tests, but I think that would be too much. WDYT?
Sample alert: https://kubeshop.slack.com/archives/C05E6GU80E7/p1689068842786839
Resolves #1125
=> Add Slack notifications for E2E tests

cmd/botkube-agent/main.go, internal/cli/install/logs/json_parser.go, internal/plugin/index_builder.go, internal/plugin/logger.go, internal/plugin/manager.go, internal/plugin/manager_test.go
- Plugins logger respect generic logger settings
- Update botkube CLI log parser to respect logrus level strings
Install Botkube, you should see a change in logs from:
```bash
WARN[2023-07-14T12:48:24Z] plugin configured with a nil SecureConfig     plugin=botkube/kubernetes
DEBU[2023-07-14T12:48:24Z] starting plugin                               args="[/tmp/botkube/source_v0.0.0-latest_kubernetes]" path=/tmp/botkube/source_v0.0.0-latest_kubernetes plugin=botkube/kubernetes
```
to 
```bash
{"level":"warning","msg":"plugin configured with a nil SecureConfig","plugin":"botkube/kubectl","time":"2023-07-14T12:59:27Z"}
{"args":["/tmp/botkube/source_v0.0.0-latest_kubernetes"],"level":"debug","msg":"starting …
```
=> Plugins logger respect generic logger settings

cmd/cli/cmd/migrate.go, cmd/cli/docs/botkube_migrate.md, internal/cli/migrate/migrate.go, internal/cli/migrate/opts.go, test/e2e/migration_test.go
- Rename `--auto-upgrade` to `--auto-approve` flag for Migration CLI
Just to unify the flags as install uses this 👍
=> Rename `--auto-upgrade` to `--auto-approve` flag for Migration CLI

.goreleaser.yml, internal/executor/helm/executor.go, internal/executor/helm/executor_test.go, internal/executor/helm/testdata/TestExecutorHelmInstallHelp.txt
- cherry pick latest bug fixes
=> Cherry-pick bug fixes to 1.2

internal/source/kubernetes/registration.go, internal/source/kubernetes/router.go, test/e2e/migration_test.go
- Fix panics in Kubernetes plugin
- Fix assertion in migration test
When I was testing Josef's PR I noticed the Kubernetes plugin panics with e.g.
<details><summary>Details</summary>
<p>
```
DEBU[2023-07-19T14:55:08+02:00] github.com/kubeshop/botkube/internal/source/kubernetes/config.(*RegexConstraints).AreConstraintsDefined(...)  plugin=botkube/kubernetes subsystem_name=botkube/kubernetes.source_v0.0.0-latest_kubernetes
DEBU[2023-07-19T14:55:08+02:00]         /home/runner/work/botkube/botkube/internal/source/kubernetes/config/config.go:97  plugin=botkube/kubernetes subsystem_name=botkube/kubernetes.source_v0.0.0-latest_kubernetes
DEBU[2023-07-19T14:55:08+02:00] github.com/kubeshop/botkube/internal/source/kubernetes.registration.matchEvent({{0x2f98920 …
```
=> Fix panics in Kubernetes plugin

cmd/botkube-agent/main.go, pkg/bot/discord.go, pkg/bot/slack_shared.go, pkg/bot/slack_socket.go
- Mapped error messages in bot packages
- There is no need to add error mapping for mattermost since they already send readable error descriptions, we use them.
Here are the screenshots for testing results for different scenarios for Slack, Discord, and Mattermost
You can create an instance on Botkube Cloud Dev, and provide wrong creds, wrong channel, or not invited channel for each platform. You need to see human-friendly messages as shown above. 
You need to run botkube deployment via `go run ...` on this branch after exporting 
```bash
export CONFIG_PROVIDER_API_KEY=...
export CONFIG_PROVIDER_ENDPOINT=https://api-dev.botkube.io/graphql
export CONFIG_PROVIDER_IDENTIFIER=...
```
https://github.com/kubeshop/botkube-cloud/issues/520
=> add human friendly error messages

cmd/executor/helm/README.md, internal/executor/doctor/executor.go, test/helpers/plugin_server.go
- change doctor plugin schema 04 to 07
- change plugin server port 3000 -> 3010 cos 3000 is usually used by react and conflicts with local UI (this is a proposal)
=> fix doctor plugin schema

.github/workflows/pr-build.yaml, .goreleaser.plugin.tpl.yaml, .goreleaser.plugin.yaml, Makefile, hack/gen-plugin-index.go, hack/target/gen-goreleaser/main.go, test/helpers/plugin_server.go
- Add tpl approach for plugin GoReleaser config
We have more and more plugins, this automates adding new plugins in the GoReleaser config.
- CI
=> Add tpl approach for plugin GoReleaser config

helm/botkube/README.md, helm/botkube/values.yaml, internal/remote/graphql/models_gen.go, internal/remote/graphql/platforms.go, internal/remote/graphql/usage.go
- Refresh GraphQL types
1. Install botkube
2. Checkout PR
3. Install CLI: `go build -o /usr/local/bin/botkube ./cmd/cli` 
4. Run: `botkube migrate --cloud-api-url http://localhost:8080/graphql`
Fix https://github.com/kubeshop/botkube/actions/runs/5819970908/job/15780045325
=> Refresh GraphQL types, add missing `flux` definition

Makefile, helm/botkube/README.md, helm/botkube/values.yaml, internal/cli/migrate/migrate.go, internal/source/keptn/source.go
- Improve JSON schema for keptn, include Flux plugin in build, fix plugin count
=> Improve JSON schema for keptn, include Flux plugin in build, fix plugin count

internal/source/github_events/config.go, internal/source/github_events/event_types.go, internal/source/github_events/github_events.go, internal/source/github_events/jsonschema.json, internal/source/github_events/templates/templates.go
- Improve gh jsonschema, 
- fix gh watch loop, 
- allow watching all prs events
=> Improve gh jsonschema, fix gh watch loop, allow watching all prs events

internal/command/guard.go, internal/command/guard_test.go
- Handle K8s empty resource list for K8s 1.26+
**NOTE:** It should be cherry picked for 1.3.1 too.
> NOTE: I tried to follow the instruction from previous similar PR: https://github.com/kubeshop/botkube/pull/834
Even with older KEDA 2.9 couldn't reproduce that on K8s 1.27. Maybe that was fixed on Kubernetes side too? 🤔 Anyway, I added a unit test to cover this.
Install Botkube with the following overrides:
```
--set image.repository=kubeshop/pr/botkube \
--set image.tag=1194-PR \
```
Resolves https://github.com/kubeshop/botkube/issues/1173
=> Handle K8s empty resource list for K8s 1.26+

cmd/cli/cmd/config/config.go, cmd/cli/cmd/config/get.go, cmd/cli/cmd/install.go, cmd/cli/cmd/migrate.go, cmd/cli/cmd/root.go, cmd/cli/cmd/uninstall.go, cmd/cli/docs/botkube.md, cmd/cli/docs/botkube_config.md, cmd/cli/docs/botkube_config_get.md, cmd/cli/docs/botkube_migrate.md, cmd/config-exporter/main.go, go.mod, internal/cli/config.go, internal/cli/config/get.go, internal/cli/install/install.go, internal/cli/login/login.go, internal/cli/migrate/migrate.go, internal/cli/migrate/opts.go, internal/cli/printer/format.go, internal/cli/printer/json.go, internal/cli/printer/resource.go, internal/cli/printer/yaml.go
- Add config get CLI command
1. Build CLI: `go build -o /usr/local/bin/botkube ./cmd/cli`
2. Run: `botkube config get` or `botkube config get -ojson` or `botkube config get -v`
- https://github.com/kubeshop/botkube-docs/issues/235
=> Add config get CLI command

.github/workflows/enforce-labels.yml
We generate changelog automatically by using pull-reqest's labels, without them everything goes into "others" section making this changelog harder to read.
Introduced actions should forbid merging PRs without labels in case if someone forgot to add some.
Previous run when labels were removed: https://github.com/kubeshop/botkube/actions/runs/6023709284/job/16340963084?pr=1219
After merging I will add enforce label job as required.
=> Add GitHub action to enforce labels

Makefile, hack/target/build-plugins/main.go, internal/plugin/downloader.go, test/fake/plugin_server.go
- Fix downloader for non archived plugins
1. Build plugins: `PLUGIN_TARGETS="cm-watcher,echo" make build-plugins-single`
2. Run server: `env PLUGIN_SERVER_HOST=http://host.k3d.internal go run test/helpers/plugin_server.go`
3. Run Botkube with config similar to:
```yaml
default-group:
socketSlack:
enabled: true
channels:
default:
name: random
bindings:
sources:
- cm-watcher
executors:
- echo
appToken: "xapp-1-"
botToken: "xoxb-"
sources:
'cm-watcher':
botkube/cm-watcher:
enabled: true
config:
configMap:
name: cm-watcher-trigger
namespace: botkube
event: ADDED
executors:
echo:
botkube/echo:
enabled: true
config:
changeResponseToUpperCase: true
plugins:
repositories:
botkube:
url: http://host.k3d.internal:3010/botkube.yaml
settings:
log: …
```
=> Fix downloader for non archived plugins

helm/botkube/README.md, helm/botkube/values.yaml
- Exluded error-like GKE node maintenance events.
https://github.com/kubeshop/botkube/issues/1167
=> Ignore error-like GKE node maintenance events

internal/executor/flux/executor.go, internal/executor/flux/jsonschema.json, internal/source/github_events/github_events.go, internal/source/github_events/jsonschema.json, internal/source/github_events/render_opts.go
- Fix schemas for gh-events and flux, 
- Fix render in gh-events
- Add raw object for automations
As described here: https://docs.botkube.io/usage/executor/flux#simplified-kustomization-diffing-flow
FYI: changes are already published to `app.botkube.io` please use it during testing. I had to do it as the important flux tutorial will be promoted today. And based on Maria feedback we already got traction on this integration so we need to have it working e2e.
Fix https://github.com/kubeshop/botkube/issues/1222
=> Fix schemas for gh-events and flux, fix render in gh-events

internal/executor/flux/commands.go, internal/executor/flux/executor.go, internal/executor/flux/forbidden.go, pkg/pluginx/command.go, pkg/pluginx/command_opts.go
- Fix help flag error, remove color codes
1. `env PLUGIN_SERVER_HOST=http://host.k3d.internal go run test/helpers/plugin_server.go`
2. `PLUGIN_TARGETS="flux" make build-plugins-single`
3. Botkube config:
```yaml
default-group:
socketSlack:
enabled: true
channels:
default:
name: hakuna-matata
bindings:
sources: []
executors:
- flux
appToken: "xapp-1-"
botToken: "xoxb-"
executors:
flux:
botkube/flux:
enabled: true
config:
log:
level: "debug"
context:
rbac:
group:
type: Static
static:
values: [ "system:masters" ]
plugins:
cacheDir: "/tmp/plugins"
repositories:
botkube:
url: http://host.k3d.internal:3010/botkube.yaml
settings:
log:
level: "debug"
formatter: "text"
clusterName: "labs"
upgradeNotifier: false
analytics:
disable: true …
```
=> Fix help flag error, remove color codes

cmd/botkube-agent/main.go, cmd/executor/echo/main.go, cmd/source/cm-watcher/main.go, helm/botkube/README.md, helm/botkube/e2e-test-values.yaml, helm/botkube/values.yaml, internal/plugin/health_monitor.go, internal/plugin/index_builder.go, internal/plugin/manager.go, internal/plugin/manager_test.go, internal/plugin/store.go, internal/source/dispatcher.go, internal/source/scheduler.go, internal/source/scheduler_test.go, internal/source/testdata/TestStartingUniqueProcesses/config.yaml, pkg/config/config.go, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/execute/config_test.go
- Restart crashed plugins based on  https://github.com/kubeshop/botkube/pull/1204
- still todo:
- add option to print plugin status or add it to list executors/sources as a new column
- add e2e tests cases
- update documentation
Co-authored-by: Josef Karasek <josef@kubeshop.io>
=> Restart crashed plugins

internal/source/argocd/argocd.go, internal/source/argocd/default-config.yaml, internal/source/argocd/render.go, internal/source/argocd/render_test.go, internal/source/argocd/setup_notifications.go, internal/source/incoming_webhook.go
- Fix ArgoCD template name normalization
- Fix incoming webhook for handling `/` characters in the source name
Use instruction from https://github.com/kubeshop/botkube/pull/1220, but instead of argocd source config name, try to use something like, e.g. `argocd/BK`. Use the name both in Helm chart and the values.yaml for overrides.
#1175
=> Fix ArgoCD template name normalization

internal/source/kubernetes/registration.go, internal/source/kubernetes/router.go, internal/source/kubernetes/router_test.go, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/override-fields-config.yaml, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-apps.v1.deployments.golden.yaml, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.configmaps.golden.yaml, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.pod.golden.yaml
- I tried to add some linter to warns when assigning the address of the variable from `range`, but unfortunately, none were able to catch this because we are passing that pointer to a function. Even [`revive`](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-address).
It's a valid candidate for cherry-picking into v1.4.1 release.
Writing manual compare was too slow, so first I used 
```go
dump = litter.Options{
StripPackageNames:         true,
HidePrivateFields:         false,
HideZeroValues:            true,
DisablePointerReplacement: true,
Separator:                 " ",
}
dump.Sdump(router.table)
```
but this was not producing readable enough assets, so I decided to go with YAML, but for that I had to export fields. …
=> Fix merging Kubernetes configuration

internal/source/dispatcher.go
The problem only occurs when you have both things:
- `socketSlack` enabled
- the same binding used both, under `socketSlack` and `elasticsearch`
-- 
Technical explanation:
1. `socketSlack` supports interactivity, such as buttons, dropdowns etc.
1. all other platforms don’t support that yet
1. sinks such as elastic or webhook doesn't support interactivity because they are one directional.
When socketSlack and other non-interactive platform are enabled and uses the same source configuration, we start 2 process:
- with indication that events can include interactive elements
- with indication that it should produce plain events
So a given event e.g. create is produced twice and we route them to a given supported platform. Unfortunately, we had a bug and for sinks we were routing both events, …
=> Fix dispatching events for sink platforms

helm/botkube/README.md, helm/botkube/values.yaml, internal/plugin/manager.go, pkg/config/config.go, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/sink/elasticsearch.go
- Fix setting type for ES index
- Add ES client logging
- Improve plugin URL err
- for ES use information on https://docs.botkube.io/community/contribute/elasticsearch-develop
- for OpenSearch you can run docker:
```
docker run --name opensearch --rm -d -p 9200:9200 -e http.port=9200 -e discovery.type=single-node -e http.max_content_length=10MB -e http.cors.enabled=true -e http.cors.allow-origin=\* -e http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -e http.cors.allow-credentials=true opensearchproject/opensearch:1.2.4
```
and open:
```
https://dejavu.reactivesearch.io/?appname=botkube-2023-09-19&url=https://admin:admin@localhost:9200&mode=edit
```
For ES you can also use the same UI.
Remember for …
=> Fix ES type setting, add ES client logging, improve plugin URL err

.github/workflows/branch-build.yml, .github/workflows/chart-testing.yaml, .github/workflows/ci.yml, .github/workflows/codeql.yaml, .github/workflows/cut-new-release.yml, .github/workflows/finalize-release.yml, .github/workflows/next-rc.yml, .github/workflows/pr-build.yaml, .github/workflows/process-chart.yml, .github/workflows/release.yml, .github/workflows/upload-plugins.yaml, .github/workflows/vulnerability-scan.yml
- actions/checkout@v3 -> actions/checkout@v4
- goreleaser/goreleaser-action@v3 -> goreleaser/goreleaser-action@v5
- goreleaser/goreleaser-action@v2 -> goreleaser/goreleaser-action@v5
- actions/setup-go@v3 -> actions/setup-go@v4
- docker/setup-qemu-action@v2 -> docker/setup-qemu-action@v3 
- docker/setup-qemu-action@v1 -> docker/setup-qemu-action@v3
- https://github.com/kubeshop/botkube/actions/runs/6247237725: 
```
- The following actions uses node12 which is deprecated and will be forced to run on node16: docker/setup-qemu-action@v1, goreleaser/goreleaser-action@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
bumping deps should resolve that
- …
=> Cancel previous runs, bump CI deps, migrate set-output

.github/workflows/chart-testing.yaml, .github/workflows/ci.yml, .github/workflows/codeql.yaml, .github/workflows/pr-build.yaml, .github/workflows/vulnerability-scan.yml
- Fix concurrent PR jobs
For `pull_request_target` event, `github.ref` is always `refs/heads/main`.
#1269
=> Fix concurrent PR jobs

helm/botkube/templates/communicationsecret.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/templates/global-config.yaml, helm/botkube/templates/persistent-config.yaml
- Fix configuration merging when using `existingCommunicationsSecretName`
- Do not create unused ConfigMaps when using remote config
See the instruction in #1273 and test the values:
```yaml
existingCommunicationsSecretName: "comm-config.yaml"
settings:
clusterName: "devops.azure.akelius.com"
sources:
k8s-custom:
botkube/kubernetes:
config:
event:
types:
- error
namespaces:
include:
- kube-infrastructure
resources:
- type: v1/pods
context:
rbac:
group:
prefix: ""
static:
values:
- botkube-plugins-default
type: Static
enabled: true
displayName: Kubernetes Errors Kube Infra
resources:
limits:
cpu: 100m
memory: 512Mi
requests:
cpu: 10m
memory: 136Mi
```
Also, test the following scenarios:
- Remote config
- Using default Communications secret - you can …
=> Fix configuration merging when using `existingCommunicationsSecretName`

.golangci.yml, Makefile, helm/botkube/e2e-cloud-test-values.yaml, helm/botkube/e2e-test-values.yaml, test/botkubex/botkube_cli_helpers.go, test/commplatform/discord_tester.go, test/commplatform/generic.go, test/commplatform/slack_tester.go, test/e2e/bots_test.go, test/e2e/gql_client.go, test/e2e/slack_helpers_test.go
- Introduced cloud-based slack e2e test
https://github.com/kubeshop/botkube/issues/865
=> Cloud Slack E2e Tests

cmd/botkube-agent/main.go, internal/health/health.go, internal/health/health_test.go, internal/health/status.go, pkg/bot/bot.go, pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack_cloud.go, pkg/bot/slack_cloud_test.go, pkg/bot/slack_legacy.go, pkg/bot/slack_socket.go, pkg/bot/teams.go, pkg/notifier/sink.go, pkg/sink/elasticsearch.go, pkg/sink/webhook.go
- add more details to healthz endpoint
- make bot connected to all available platforms
- run bot-agent and trigger /healthz endpoint
#890
=> Healthz improve endpoint

.github/workflows/publish-chart.yml
- Typo fix in main helm chart release
=> Fix main chart version

.github/workflows/upload-plugins.yaml
For [the latest plugin release](https://storage.googleapis.com/botkube-plugins-latest/plugins-index.yaml), we use only archive plugins on index.yaml. However, we still push both the binaries and archives making the bucket size to grow.
- Upload only plugin archives as latest plugins
Tested on CI branch: https://github.com/kubeshop/botkube/actions/runs/6455472645/job/17523021491?pr=1287
```
▲ gsutil du -s -h gs://botkube-plugins-latest                                                                                                            2s
1.38 GiB     gs://botkube-plugins-latest
▲ gsutil du -s -h "gs://botkube-plugins-latest/*.tar.gz"
685.12 MiB   gs://botkube-plugins-latest/*.tar.gz
▲ gsutil du -s -h -e "*.tar.gz" gs://botkube-plugins-latest/ …
```
=> Upload only plugin archives as latest plugins

.github/workflows/branch-build.yml, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
- Fix Cloud Slack Dev E2E tests after Botkube release
- Take into account the "upgrade checker" message
No need, the pipeline tests it: https://github.com/kubeshop/botkube/actions/runs/6457080833
=> Fix Cloud Slack Dev E2E tests after Botkube release

cmd/botkube-agent/main.go, internal/analytics/noop_reporter.go, internal/analytics/reporter.go, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportBotEnabled.json, internal/analytics/testdata/TestSegmentReporter_ReportCommand.json, internal/analytics/testdata/TestSegmentReporter_ReportSinkEnabled.json, internal/source/dispatcher.go, pkg/bot/bot.go, pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack_cloud.go, pkg/bot/slack_legacy.go, pkg/bot/slack_socket.go, pkg/bot/teams.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/sink/elasticsearch.go, pkg/sink/types.go, pkg/sink/webhook.go
- Include full plugin name in reported command
- Report communication group anonymous ID
- Report Cloud Slack enabled
No need, unit tests properly test it.
But, you can change the NoopReporter to:
```go
func (n NoopReporter) ReportBotEnabled(p config.CommPlatformIntegration, i int) error {
fmt.Println(">>", p, i)
return nil
}
// ReportSinkEnabled reports an enabled sink.
func (n NoopReporter) ReportSinkEnabled(p config.CommPlatformIntegration, i int) error {
fmt.Println(">>", p, i)
return nil
}
// ReportCommand reports a new executed command. The command should be anonymized before using this method.
func (n NoopReporter) ReportCommand(in ReportCommandInput) error {
formatx.StructDumper().Dump("ReportCommandInput", in)
return nil
}
```
And execute a …
=> Include full plugin name in reported command

pkg/bot/teams_cloud_grpc.go
- Added remote config identifier to cloud ms teams settings
Relates https://github.com/kubeshop/botkube-cloud/pull/681
=> Cloud MS Teams now using remote cfg

.github/workflows/publish-chart.yml
- Branch build uses fecth dept 0, updated char publish as same to have same commit sha
=> Fecth depth set for correct commit id

internal/source/github_events/json_matcher.go, internal/source/github_events/jsonschema.json
- Add opt to use regex for json path values
- Docs: https://github.com/kubeshop/botkube-docs/pull/293
Config:
```
repositories:
- name: mszostok/gh-test-repo
on:
events:
- type: "IssueCommentEvent"
jsonPath: ".comment.html_url"
value: ".*/pull.*"
notificationTemplate:
previewTpl: |-
Commented on #{{ .Issue.Number }} {{ .Issue.Title }}
State:   {{ .Issue.State }}
Comment: {{ .Comment.Body }}
extraButtons:
- displayName: Open
url: "{{ .Issue.HTMLURL }}"
style: primary
```
=> Add opt to use regex for json path values

pkg/bot/slack_cloud.go, pkg/bot/teams_cloud.go
- Added additional logs for grpc connection
- Set timeout for grpc connection methods since somehow retry mechanism somehow stuck on second retry after 502 server response and it keeps ctx open infinitely
=> Additional logs for the grpc conn.

internal/remote/graphql/connected_platforms.go, internal/remote/graphql/models_gen.go, internal/remote/graphql/platforms.go, internal/remote/graphql/usage.go, pkg/bot/teams_cloud.go, pkg/bot/teams_cloud_test.go, pkg/execute/command/origin.go
- Add user display name for interactive command responses.
- Introduce a feature that allows explicit origin extraction for the execution of commands. Furthermore, for commands that do not have an explicit origin property, a fallback strategy has been implemented to determine the command origin based on activity type.
Fix https://github.com/kubeshop/botkube-cloud/issues/739
=> Add origin extraction for cmd execution, add user display name for interactive command

pkg/bot/slack_cloud.go, pkg/bot/teams_cloud.go, pkg/bot/teams_cloud_grpc.go, pkg/config/config.go, pkg/grpcx/credentials.go
- Support TLS encryption for gRPC connections in Cloud Slack and Teams
Test it E2E with the changes on Cloud.
=> Support TLS encryption for gRPC connections in Cloud Slack and Teams

pkg/config/config.go, pkg/execute/config.go
- Fix redacting credentials when showing config
- Hide CA cert as it makes the config unreadable
=> Fix redacting credentials and hide CA certificate when showing config

CONTRIBUTING.md, Makefile
- Remove `make build` target since it's not used anywhere.
- Make sure botkube agent binary is name `botkube-agent`.
- Incidental markdown lint fixes.
=> Fix slight confusion in agent built bin name

internal/source/dispatcher.go
- Forward action output to sinks
You can try this tutorial: https://docs.szostok.io/botkube-plugins/sources/incoming-http
=> Forward action output to sinks

go.mod, go.sum, internal/executor/doctor/config_schema.json, internal/executor/doctor/executor.go
- Update Doctor's engine to `gpt-3.5-turbo-instinct` and fix prompt
https://github.com/kubeshop/botkube/assets/7155799/96dd7630-6ddd-4ffb-a34f-c722bdd1d947
Checkout this PR:
```bash
gh pr checkout 1349
```
Run plugins server:
```bash
make build-plugins-single
go run test/helpers/plugin_server.go
```
Prepare `comm_config.yaml`:
```yaml
settings:
clusterName: "dev"
plugins:
repositories:
botkube:
url: http://localhost:3010/botkube.yaml
executors:
k8s-default-tools:
botkube/kubectl:
enabled: true
botkube/helm:
enabled: true
"ai":
botkube/doctor:
enabled: true
config:
apiKey: "..."
sources:
k8s-err-events:
botkube/kubernetes:
enabled: false
k8s-err-events-with-ai-support:
displayName: "Kubernetes Errors with AI support"
botkube/kubernetes:
context:
rbac: …
```
=> Update Doctor's engine to `gpt-3.5-turbo-instinct` and fix prompt

.github/workflows/branch-build.yml, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
- Improve Cloud Slack e2e test resiliency
After connecting Slack workspace, the homepage sometimes isn't able to fully load. I'm not sure why, that's why this PR introduces:
- screenshot after connecting Slack workspace, when homepage can't be loaded
- continuing the tests with an error, to make sure the Slack workspace is properly disconnected
No need - CI verifies it:
- https://github.com/kubeshop/botkube/actions/runs/7556642651/job/20574105015?pr=1352
- https://github.com/kubeshop/botkube/actions/runs/7556642651/attempts/1
=> Improve Cloud Slack e2e test resiliency around Slack workspace connect

cmd/cli/cmd/migrate.go, cmd/cli/docs/botkube_migrate.md, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go, test/e2e/migration_test.go
- Fix Botkube version constraint during migration
- Update E2E migration test to cover the case for two executors under executor config group
The actual issue:
```
FATA while running application: while merging app configuration: found critical validation errors: 3 errors occurred:
* Key: 'Config.Actions[show-logs-on-error].Bindings.k8s-default-tools_jJkwz' 'k8s-default-tools_jJkwz' binding not defined in Config.Executors
* Key: 'Config.Actions[describe-created-resource].Bindings.k8s-default-tools_jJkwz' 'k8s-default-tools_jJkwz' binding not defined in Config.Executors
```
has been resolved on Cloud side.
Test this against Botkube Cloud dev setup.
Check out the PR and build the latest CLI:
```bash
export IMAGE_TAG=v9.99.9-dev
make release-snapshot-cli …
```
=> Fix Botkube version constraint during migration

helm/botkube/README.md, helm/botkube/values.yaml, internal/cli/install/helm/install.go, internal/cli/install/install.go, internal/cli/migrate/converter.go, pkg/config/config.go, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/config/testdata/TestLoadConfigSuccess/executors.yaml
- migrate disabled plugin
- fix missing displayName during migration
- fix RBAC conversion
- fix installation command abort update existing instalation
Test this against Botkube Cloud dev setup (UI and BE).
Check out the PR and build the latest CLI:
```
export IMAGE_TAG=v9.99.9-dev
make release-snapshot-cli
chmod +x ./dist/botkube-cli_darwin_amd64_v1/botkube && cp ./dist/botkube-cli_darwin_amd64_v1/botkube /usr/local/bin/botkube_dev
```
Then, install Botkube in your k3d cluster
```
export ALLOW_KUBECTL=true
export ALLOW_HELM=true
export SLACK_CHANNEL_NAME=botkube-demo \
export SLACK_API_APP_TOKEN=xapp-... \
export SLACK_API_BOT_TOKEN=xoxb-... \
export CLUSTER_NAME=dev
botkube_dev install --version 1.7.0 \
--set …
```
=> Migrate disabled plugins to Cloud

cmd/cli/cmd/migrate.go, go.mod, internal/cli/migrate/compatibility.go, internal/cli/migrate/compatibility_test.go
- Reorganize migrate constaints check and add unit tests
After I found out an issue on 1.8.0-rc.1, I've reorganized the code a bit and also wrote some unit tests to check how it behaves.
Unfortunately this is a known issue https://github.com/Masterminds/semver/issues/177, but as we can encounter it only on RC versions, I think it's a very low priority one.
This PR doesn't need to be cherry-picked for final 1.8.
See test instruction from https://github.com/kubeshop/botkube/pull/1353
=> Reorganize migrate constaints check and add unit tests

.github/actions/setup-go-mod-private/action.yaml, .github/workflows/branch-build.yml, .github/workflows/ci.yml, .github/workflows/codeql.yaml, .github/workflows/pr-build.yaml, .github/workflows/release.yml, .github/workflows/upload-plugins.yaml, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go, test/commplatform/discord_tester.go, test/commplatform/generic.go, test/commplatform/slack_tester.go, test/commplatform/teams_tester.go
- Update setup-go action, a follow-up from https://github.com/kubeshop/botkube/pull/1372#discussion_r1483093276
=> Update setup-go action

cmd/botkube-agent/main.go, internal/analytics/noop_reporter.go, internal/analytics/reporter.go, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportPluginsEnabled.json, internal/plugin/kubeconfig.go, pkg/config/config.go
- Report to Segment plugins RBAC configuration
- In `internal/analytics/segment_reporter.go:36` set APIKey (you can find it here: https://app.segment.com/kubeshop-dev-botkube/sources/botkube_agent/settings/keys)
- Run botkube agent
- Open Segment Debuger https://app.segment.com/kubeshop-dev-botkube/sources/botkube_agent/debugger
- Check if you can see a new event `PluginConfig`
- https://github.com/kubeshop/botkube-cloud/issues/836
- PR on botkube-docs (update privacy policy) https://github.com/kubeshop/botkube-docs/pull/308
=> Enabled Plugins Report

helm/botkube/templates/persistent-config.yaml
Bug in the Helm chart when using existing secret
`Error: template: sre-botkube/charts/botkube/templates/persistent-config.yaml:6:23: executing "sre-botkube/charts/botkube/templates/persistent-config.yaml" at <index $secret.data "comm_config.yaml">: error calling index: index of untyped nil`
Fixes #1376.
=> Fix Helm chart upgrade when using existing secret

.github/actions/cloud-slack-e2e/action.yaml, .github/workflows/branch-build.yml, .github/workflows/prod-e2e-test.yml
- Use only the `${{ secrets.SLACK_CI_ALERTS_WEBHOOK }}` webhook the `${{ secrets.SLACK_PROD_ALERTS_WEBHOOK }}` is redundant and will be removed.
- Make the cloud Slack notification footer more useful
- Skip not needed steps for discord integration tests
-  Remove invalid strategy on the `cli-migration-e2e` job
Done by CI, example notifications, instead of generic `Fingers crossed it's just an outdated/flaky test...` I print what step actually failed. I did that only for cloud for now:
- https://github.com/kubeshop/botkube/actions/runs/7900714366/job/21562806733
-  I failed it on purpose
=> Enhance Slack notification footer

cmd/botkube-agent/main.go
- Ignore upgrade checker error, otherwise engine cannot start until e.g. rate limit is reset:
```
[OS]     https://api.github.com/repos/kubeshop/botkube/releases/latest: 403 API rate limit exceeded for 188.147.12.104. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 48m53s]
```
This can be done using HEAD request, that doesn't count against rate limits, I can do it in the follow-up, see example: https://github.com/mszostok/version/blob/a69cf43b345ccd616da915912e2dc9deb8bfc992/upgrade/github/head_fetch.go#L23-L54
=> Ignore upgrade checker error

helm/botkube/README.md, helm/botkube/values.yaml, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportPluginsEnabled.json, internal/executor/kubectl/executor.go, internal/source/kubernetes/config_schema.json
- Fix overwriting custom RBAC config
- Fix Kubernetes `extraButtons` schema
- Remove unused properties
You can run the updated unit test before and after the fix.
=> Fix overwriting custom RBAC config and Kubernetes plugin JSON schema

helm/botkube/templates/persistent-config.yaml
- Fix Helm chart upgrade when `lookup` is not supported
I don't think it's needed to test it but if you want to, see the instruction from https://github.com/kubeshop/botkube/pull/1274
See conversation: https://botkube.slack.com/archives/C01CR1KS55K/p1709740107856559
See also: https://github.com/kubeshop/botkube/issues/1376
=> Fix Helm chart upgrade when `lookup` is not supported

.github/actions/cloud-slack-e2e/action.yaml, .github/actions/dump-cluster/action.yaml, .github/workflows/branch-build.yml, .github/workflows/pr-build.yaml, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go, test/e2e/bots_test.go, test/helmx/helm_helpers.go, test/helmx/redact_test.go
- Force remove Cloud resources when Botkube uninstall timeouts
- Do not uninstall Botkube on failure, always dump logs
- Fix waiting on bot after restart
- Fix overwriting artifacts from multiple jobs
- Fix waiting for Botkube Helm chart uninstall
No need to do it, CI tests it.
- Slack: https://github.com/kubeshop/botkube/actions/runs/8205276642/job/22441872428?pr=1406
- Discord: https://github.com/kubeshop/botkube/actions/runs/8205276642/job/22441872686?pr=1406
- Teams: https://github.com/kubeshop/botkube/actions/runs/8205276642/job/22441872995?pr=1406
- Dev E2E Cloud Slack: https://github.com/kubeshop/botkube/actions/runs/8205276255/job/22441772142?pr=1406
=> Improve resilience of E2E and integration tests

.github/workflows/branch-build.yml, .github/workflows/prod-e2e-test.yml, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
- Reduce number of prod tests, add missing error assertions
=> Reduce number of prod tests, add missing error assertions

pkg/bot/slack_cloud.go
- Fix sending AI file response into a given thread
- Fix setting ack emoji 
- Fix sending empty responses when file doesn't have filter:
```
ERRO[2024-03-11T14:24:09+01:00] while sending bot message: 1 error occurred:
* while sending Slack message to channel "general": while posting Slack message: no_text
```
1. Start a new thread: `@Botkube ai hi!`
2. Ask for long msg: `@Botkube ai send an example post-mortem document that has at least 3500 chars`
Fix https://github.com/kubeshop/botkube-cloud/issues/942
=> Fix sending file messages in Cloud Slack

CONTRIBUTING.md, Makefile, internal/source/kubernetes/config/config.go, internal/source/kubernetes/filterengine/filterengine.go, internal/source/kubernetes/msg.go, internal/source/kubernetes/msg_test.go, internal/source/kubernetes/source.go, pkg/config/config.go, pkg/loggerx/logger.go
- Only log incorrect k8s buttons definitions
- Agent without debug enabled, shows k8s plugin errors too.
You can see the unit-test, additionally I tested that e2e:
- when Agent uses `text` logger:
```text
ERRO[2024-03-11T18:17:30+01:00] ERRO[2024-03-11T18:17:30+01:00] Failed to convert extra buttons assigned to "error" event. Those buttons will be omitted. Issues:  logger=stderr plugin=botkube/kubernetes
ERRO[2024-03-11T18:17:30+01:00] 3 errors occurred:                            logger=stderr plugin=botkube/kubernetes
ERRO[2024-03-11T18:17:30+01:00] 	* invalid extraButtons[1].commandTpl: template: Ask AI v2:1:11: executing "Ask AI v2" at <.Event.Namespace>: can't evaluate field Event in type event.Event  logger=stderr plugin=botkube/kubernetes …
```
=> Only log incorrect k8s buttons definitions

cmd/botkube-agent/main.go, internal/source/dispatcher.go, internal/source/kubernetes/bg_processor.go, internal/source/kubernetes/configuration_store.go, internal/source/kubernetes/filterengine/filterengine.go, internal/source/kubernetes/registration.go, internal/source/kubernetes/router.go, internal/source/kubernetes/router_test.go, internal/source/kubernetes/source.go, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-apps.v1.deployments.golden.yaml, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.configmaps.golden.yaml, internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.pod.golden.yaml, internal/source/scheduler.go
- Reduce memory consumption for Kubernetes source configuration
This change groups Kubernetes source configurations by different kubeconfigs and creates a single `dynamicInformerFactory` per group, which essentially brings the implementation close to the 0.18 Kubernetes source one. 
Memory consumption shortly after startup:
| Description | v1.9.1 | This PR |
|--------|--------|--------|
| No sources enabled | 21.4 MiB | 23.1 MiB |
| 1 source (`k8s-all-events2` from the PR instruction) | 78.9MiB | 86.6 MiB |
| 12 sources (from the PR instruction) | 504MB |  92.9 MiB |
12 sources:
Too low, source plugin restarts itself.
Plugin runs withourt restarting, still multiple DeltaFIFO logs
Requests 128Mi, limit 256Mi:
No DeltaFIFO logs, just a warning about …
=> Reduce memory consumption for Kubernetes source configuration

test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go, test/cloud_graphql/graphql_client.go, test/e2e/bots_test.go, test/go.mod
- Add retries for resources cleanup in Botkube E2E and integration tests
=> Add retries for resources cleanup in Botkube E2E and integration tests

pkg/execute/executor.go, pkg/execute/params.go, pkg/execute/params_test.go
- Add single quote escaping while parsing input command. It's more like a workaround.  Ultimately, we should find a better and more generic way for extracting parameters. Additionally, we should delegate command tokenizing to the plugin. However, this would require a bigger refactor, so I deduced to not go into that direction right now.
- https://github.com/kubeshop/botkube-cloud/issues/994
=> Add single quote escaping while parsing input command

pkg/api/message.go
- Add `api.BasicCardWithButtonsInSeparateMsg` type
- https://github.com/kubeshop/botkube-cloud/issues/1025
=> Add `api.BasicCardWithButtonsInSeparateMsg` type

cmd/botkube-agent/main.go, go.mod, go.sum, internal/source/scheduler.go, pkg/config/config.go, pkg/plugin/collector.go, pkg/sink/pager_duty.go, pkg/sink/pager_duty_meta.go, pkg/sink/pager_duty_test.go, test/go.mod, test/go.sum
- Add PagerDuty integration platform
1. Create cluster
2. [Install ArgoCD and create example app](https://argo-cd.readthedocs.io/en/stable/getting_started/)
3. [Create PagerDuty service](https://add-pager-duty.botkube-docs.pages.dev/next/installation/pagerduty/#create-a-pager-duty-service)
4. Change the argocd plugin to get rid of cloud check (we need to use local `values.yaml`)
4. Build plugin: `PLUGIN_TARGETS='argocd' make build-plugins-single`
4. Serve plugin: make serve-local-plugins
4. Use such configuration:
```yaml
default-group:
pagerDuty:
enabled: true
integrationKey: 'key'
bindings:
sources:
- k8s-err-events
- k8s-deploy
- argocd
sources:
argocd:
displayName: argocd
local-cloud/argocd:
enabled: true
config:
log:
level: debug …
```
=> Add PagerDuty integration platform

helm/botkube/README.md, helm/botkube/values.yaml
- Update links in Helm chart values file
=> Update links in Helm chart values file

pkg/api/message.go, pkg/bot/slack_renderer.go
- Introduce italic description for Button Builder API
The new style is used for AI plugin footer formatting.
No need to test it.
https://github.com/kubeshop/botkube-cloud/issues/1060
=> Introduce italic description for Button Builder API

pkg/bot/interactive/help.go
Part of https://github.com/kubeshop/botkube-cloud/issues/1062
- bot: add cluster scan help docs
=> bot: add cluster scan help docs

cmd/cli/docs/botkube_install.md, cmd/cli/docs/botkube_migrate.md, cmd/cli/docs/botkube_uninstall.md, internal/cli/helmx/action_cfg.go, internal/cli/install/helm/install.go, internal/cli/install/install.go, internal/cli/uninstall/helm/uninstall.go, internal/cli/uninstall/uninstall.go, internal/kubex/config.go
I will edit later. I'm still testing.
- Add support for --kube-context option into botkube CLI 
Resolves #1456
=> Add support for --kube-context option into botkube CLI

pkg/bot/slack_cloud.go, pkg/config/config.go, pkg/config/redacted.go, pkg/execute/config.go
- Hide private channel names in `show config` command
- Extend config with Cloud Slack channel ID and alias
Run the changes E2E with other pull requests. Instructions there.
https://github.com/kubeshop/botkube-cloud/issues/1165
=> Hide private channel names in `show config` command

internal/source/kubernetes/router.go, internal/source/kubernetes/router_test.go
- Fix panic on missing root event type for k8s source
Fix https://github.com/kubeshop/botkube/issues/1474
=> Fix panic on missing root event type for k8s source
