.travis.yml, helm/botkube/Chart.yaml
Add "helm lint" check to travis ci build
Update Chart.yaml with more info
=> Add "helm lint" check to travis ci build

pkg/controller/controller.go, pkg/events/events.go
Fixes: https://github.com/infracloudio/botkube/issues/63
=> Add Skip var in Event struct to skip an event

Makefile, deploy-all-in-one.yaml, helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml, pkg/execute/executor.go
Fixes: https://github.com/infracloudio/botkube/issues/62
=> Return BotKube version with response to ping

Gopkg.lock, Gopkg.toml, pkg/controller/controller.go, vendor/github.com/fsnotify/fsnotify/.editorconfig, vendor/github.com/fsnotify/fsnotify/.gitignore, vendor/github.com/fsnotify/fsnotify/.travis.yml, vendor/github.com/fsnotify/fsnotify/AUTHORS, vendor/github.com/fsnotify/fsnotify/CHANGELOG.md, vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md, vendor/github.com/fsnotify/fsnotify/LICENSE, vendor/github.com/fsnotify/fsnotify/README.md, vendor/github.com/fsnotify/fsnotify/fen.go, vendor/github.com/fsnotify/fsnotify/fsnotify.go, vendor/github.com/fsnotify/fsnotify/inotify.go, vendor/github.com/fsnotify/fsnotify/inotify_poller.go, vendor/github.com/fsnotify/fsnotify/kqueue.go, vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go, vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go, vendor/github.com/fsnotify/fsnotify/windows.go
Fixes: https://github.com/infracloudio/botkube/issues/72
=> Add logic to restart BotKube pod if config file is updated

.travis.yml, helm/botkube/Chart.yaml, helm/botkube/values.yaml
Set app version to 0.8.0-dev
Fixes #92
=> Build and push docker image from develop

hack/release.sh
Use https://github.com/itchio/gothub to automatically publish releases.
Not attaching any artifacts as of now.
Fixes #70
=> Use gothub for publishing releases

pkg/execute/executor.go, pkg/filterengine/filterengine.go, pkg/filterengine/filters/image_tag_checker.go, pkg/filterengine/filters/ingress_validator.go, pkg/filterengine/filters/job_status_checker.go, pkg/filterengine/filters/pod_label_checker.go
Show filter description while listing filters
Fixes #113
=> Add description to the filters

pkg/slack/slack.go
BotKube command doesn't need `@BotKube` prefix if posted as DM to BotKube
Fixes #115
=> Treat DM as a valid incoming message

cmd/botkube/main.go, pkg/bot/bot.go, pkg/bot/mattermost.go, pkg/bot/slack.go
- Code Refactoring
Create interface `Bot` in bot package.
All mediums should implement `Bot` interface.
=> Create bot interface for communication mediums

pkg/bot/mattermost.go
`@BotKube` prefix not needed if a command is sent as a DM to BotKube in Mattermost integration
Fixes #116
=> Serve DMs to BotKube in Mattermost

pkg/execute/executor.go
=> Trim whitespaces in the BotKube command

CONTRIBUTING.md
Update CONTRIBUTING.md to add missing build step
=> Update CONTRIBUTING.md to add missing build step

pkg/controller/controller.go, pkg/events/events.go
Fix timestamp for update events
Ignore older update events after resync
Fixes #123
=> Fix timestamp for update events

README.md
Add godoc reference badge in README
=> [Documentation] Add godoc reference badge in README

pkg/bot/mattermost.go
Signed-off-by: gangseok.lee <gangseok.lee@samsung.com>
event is nil in this case. adding nil check is needed
Fixes #126
=> fix invalid memory address or nil pointer deference on mattermost

pkg/bot/slack.go
Fixes file upload issue due to a missing parameter
Fixes #185
=> Fix file upload for Slack

pkg/filterengine/filters/job_status_checker.go
This PR fixes the issue of getting duplicate Job update notifications.
We'll be ignoring update events which are older than 30sec
=> Fix duplicate notification for Job update

helm/botkube/sample-res-config.yaml
Needed for documentation purpose
=> Add sample config referenced in the docs

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/templates/deployment.yaml, pkg/events/events.go, pkg/filterengine/filters/ingress_validator.go, pkg/utils/utils.go, test/e2e/filters/filters.go, test/e2e/utils/utils.go
Refactor code to remove deprecated K8s API groups
Fixes #191
=> Update Deprecated API groups in K8s 1.16

README.md
This Commit,
- adds Latest Release Badge to README.md
=> Add Latest Release Version Badge to README.md

config.yaml, deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml
Cherry-picked from https://github.com/infracloudio/botkube/pull/197 and updated all the config files to be in sync
Fixes #194
=> Fix namespace format in config files

hack/release.sh
=> Update image repo in release script

helm/botkube/templates/clusterrole.yaml
This removes an errant } from the helm clusterrole template
=> Remove errant } from clusterrole helm template

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/values.yaml, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/controller/controller.go, pkg/events/events.go, pkg/filterengine/filters/image_tag_checker.go, pkg/filterengine/filters/ingress_validator.go, pkg/filterengine/filters/namespace_checker.go, pkg/filterengine/filters/node_event_checker.go, pkg/filterengine/filters/pod_label_checker.go, pkg/filterengine/filters/utils.go, pkg/notify/mattermost.go, pkg/notify/slack.go, pkg/notify/webhook.go, pkg/utils/utils.go, test/e2e/e2e_test.go, test/e2e/filters/filters.go, test/e2e/notifier/create/create.go, test/e2e/utils/utils.go
- Don't skip notification for cluster scoped resources
- Move message formatting logic to notif package
- Remove secret resource from default BotKube config
- Fix notification previews in Slack and MM
Fixes #218
=> Fix cluster scoped resource notification issue

pkg/bot/mattermost.go
Mattermost server closes websocket connection sometimes. Add logic to reconnect to the websocket if broken
Fixes #201
=> Add mattermost connection retry logic

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml
Fix deploy manifest to work with latest BotKube
=> Fix deploy manifest to work with latest BotKube

pkg/filterengine/filters/node_event_checker.go, pkg/notify/slack.go
This PR,
- changes the event type created during NodeReady as InfoEvent.
- adds corresponding InfoEvent case in the notify package.
Fixes #260
=> Fix Node getting ready is reported as an error

helm/botkube/sample-res-config.yaml
Update sample resource config with updateSettings
=> Update sample resource config

.mergify.yml
Fix mergify base branch to develop
=> Fix mergify base branch to develop

helm/botkube/templates/deployment.yaml, helm/botkube/values.yaml
Capability to pass extra annotations to pod if required
=> options to pass exta annotations for pod

helm/botkube/templates/deployment.yaml
Fixing bad if block in helm deployment template for pod annotations
=> correcting annotation if block

pkg/utils/utils.go
=> Initialized the DiscoveryClient Variable

go.mod, go.sum, test/e2e/command/botkube.go, test/e2e/env/env.go, test/e2e/filters/filters.go, test/e2e/notifier/create/create.go, test/e2e/utils/utils.go, test/resource_config.yaml
- Add e2e test for Custom Resource support
- Refactor test package
Fixes #334
=> Add e2e test for Custom Resource support

pkg/controller/controller.go, pkg/events/events.go, pkg/utils/diff.go, pkg/utils/jsonpath.go, pkg/utils/utils.go
- Fix Allowed maps checks
- Update diff calculation logic
Fixes #339 #342
=> Fix update and error event skip issue

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, helm/botkube/sample-res-config.yaml, helm/botkube/values.yaml
- Update all-in-one yamls for Teams support
- Add sample res config for custom resources
=> Update all-in-one deploy yamls for Teams support

helm/botkube/README.md
=> Add helm chart README

design/multi-cluster.md, helm/botkube/values.yaml, pkg/bot/mattermost.go, pkg/config/config.go
Corrected spelling mistakes in documentation comments, changed cases for references to BotKube for consistency across docs, and added code markdown to kubectl reference for consistency
=> Fix spelling and change case in comments and docs

test/e2e/notifier/error/error.go
=> Validate error events are skipped when error event is not configured in test_config

pkg/events/events.go, pkg/filterengine/filters/namespace_checker.go
Fix namespace checker filter issue where events with ignored namespaces were not getting skipped 
Fixes #419
=> Fix namespace checker filter

pkg/bot/utils.go, test/e2e/command/botkube.go, test/e2e/command/kubectl.go
Remove whitespaces in the command responses
=> Remove whitespaces in the responses

hack/release.sh
Update changelog gen command in release script to work with the latest https://github.com/github-changelog-generator/github-changelog-generator release
=> Update github_changelog_generator to work with v1.15.2

helm/botkube/README.md, pkg/notify/elasticsearch.go
Capability to fetch AWS credentials from the EKS OIDC provider
Fixes #462
=> Generating credentials using WebhookIdentity on AWS

helm/botkube/templates/ingress.yaml
This PR holds the step to check if you are running Kubernetes with support to the new ingress apiVersion.
Fixes #XXX
=> Add support to new ingress apiVersion version.

build/Dockerfile
- Bug fix Pull Request (Security)
Changing alpine version for security,
Version 3.10 will be out of scope in a month.
=> bumping alpine version, improving security

.github/workflows/ci.yml
Make CI compatible with helm3
Fixes #474
=> Make CI compatible with helm3

.github/workflows/ci.yml
Fix helm chart publish failure in CI on master
=> [CI] Switch to helm3 to publish helm chart

.github/workflows/artifacts.yml
Fix typo in the CI make target
=> [CI] Fix make target in CI

.github/workflows/artifacts.yml
=> [CI] Add missing goreleaser action

.github/workflows/artifacts.yml
=> [CI] Fix goreleaser install action

helm/botkube/README.md
=> Update helm docs

CHANGELOG.md
Fix spelling in CHANGELOG to make spellcheck CI happy
=> Happy spellcheck CI

.github/workflows/artifacts.yml
=> [CI] Fix github token secret name

deploy-all-in-one-tls.yaml, deploy-all-in-one.yaml, hack/release.sh, helm/botkube/README.md
- Update release script to bump release tags
- Correct BotKube release versions in all in one deploy yamls
=> Update release script to bump release tags

go.mod, go.sum
Upgrade golang.org/x... pkg deps to fix CI
=> Upgrade golang.org/x... pkg deps

test/webhook/server.go
Do not log msg in tests to fix CVE checks
https://github.com/infracloudio/botkube/runs/4527109648
=> [Test] Do not log msg in tests

.github/workflows/ci.yml
Fixes #549 so vulnerabilities would be automatically reported inside CI pipeline. Scan results will be sent to GitHub Security tab as well.
=> Feature: CI vulnerability scan

go.mod, go.sum
Bump golang.org/x/crypto dep to recent version fix CI build failing on PRs
=> Bump golang.org/x/crypto dep to fix CI build

docs/investigation/analytics-collection.md, docs/investigation/analytics.md
- Investigate analytics collection
This PR contains a document with a short summary of my investigation as a part of #506.
See #506
=> Investigate analytics collection

README.md, artifacthub-repo.yml
- Add Artifact Hub meta file
- Add badge
Fixes #634
=> Add Artifact Hub meta file

CONTRIBUTING.md, README.md, build/Dockerfile, build/test.Dockerfile
- Fix image labels, remove not working go report badge
It's enough to see the `ghcr.io`:
**botkube:**
- previously: https://github.com/kubeshop/botkube/pkgs/container/pr%2Fbotkube/29955262?tag=662-PR-armv7
- now: https://github.com/kubeshop/botkube/pkgs/container/pr%2Fbotkube/29956951?tag=665-PR-arm64
**botkube-test:**
- previously: https://github.com/kubeshop/botkube/pkgs/container/pr%2Fbotkube-test/29955272?tag=662-PR
- now: https://github.com/kubeshop/botkube/pkgs/container/pr%2Fbotkube-test/29956971?tag=665-PR
=> Fix image labels, remove not working go report badge

pkg/execute/kubectl/merger.go, pkg/execute/kubectl/merger_test.go
- Fix merging order for executor bindings
#596
=> Fix merging order for executor bindings

helm/botkube/README.md, helm/botkube/values.yaml
- Update Helm chart values description
Fix for failing tests in #680 
#596
=> Update Helm chart values description

.github/CODEOWNERS
- Added @huseyinbabal as a code owner.
N/A
=> Add new code owner(@huseyinbabal)

.github/workflows/ci.yml, go.mod, internal/analytics/segment_reporter_test.go, pkg/config/config.go, pkg/execute/executor.go, pkg/execute/kubectl.go, pkg/utils/utils.go
- Go is upgraded to 1.19
- Linter errors are fixed
=> Go 1.19 Upgrade

.goreleaser.yml, hack/release.sh
- Generate only draft release, and process chart during release
=> Generate only draft release, and process chart during release

helm/botkube/templates/ingress.yaml, pkg/config/config.go, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/execute/notifier.go
- Fix ingress manifest
- Hide the MS Teams password
- Remove not used `team` property in MS Teams cfg
- https://github.com/kubeshop/botkube/issues/595
=> Fix ingress manifest

examples/README.md, examples/ingress-recommendations/README.md, examples/ingress-recommendations/botkube-values.yaml, examples/ingress-recommendations/deploy-final/meme.yaml, examples/ingress-recommendations/deploy-final/quote.yaml, examples/ingress-recommendations/deploy/meme.yaml, examples/ingress-recommendations/deploy/quote.yaml, examples/ingress-recommendations/ingress-overrides.yaml
- Prepare Ingress recommendation example
This example contains a demo scenario centered around the BotKube recommendation feature.
=> Prepare Ingress recommendation example

examples/README.md, helm/botkube/README.md, helm/botkube/values.yaml
- Revert image tag to the dev one. This was done by the release scripts but it won't happen after https://github.com/kubeshop/botkube/issues/584
- #595
=> Revert image tag to the dev one

docs/investigation/configuration/2022-09-07-persistent-cfg-from-commands.md, docs/investigation/configuration/assets/communicationsecret.yaml
- Investigate persistent configuration for BotKube commands
See #704
=> Investigate persistent configuration for BotKube commands

.github/workflows/pr-build.yaml
- Fix missing slash in command
=> Fix missing slash in command

.github/workflows/pr-build.yaml
- Add slack app level token injection for pr build
=> fix: slack app token injection during pr build

.github/workflows/branch-build.yml, .github/workflows/pr-build.yaml, helm/botkube/e2e-test-values.yaml, test/e2e/bots_test.go, test/e2e/discord_driver_test.go, test/e2e/slack_driver_test.go
- Adds e2e-test-values with correct discord notification settings.
- Updates Github Actions with missing Discord `BotToken` and `BotID` config.
https://github.com/kubeshop/botkube/issues/307
=> Fix Discord e2e tests.

pkg/bot/interactive/feedback.go, pkg/bot/socketslack.go, pkg/execute/executor.go
This is a small PR to address "minor issues" that I spot recently.
- Fix typo in feedback
- Remove redundant func args
=> Fix typo in feedback, remove redundant func args

.github/workflows/cut-new-release.yml
- Main branch is left as `automate-release`, it is reverted
=> Revert main branch

pkg/bot/slack.go, pkg/bot/socketslack.go
- File upload thread reply problem fixed
Fixes #816
=> Response thread fix

pkg/execute/executor.go
- Updated placeholder for `Filter Output` as `String pattern to filter by`
=> filter output placeholder change

pkg/bot/socketslack.go, pkg/execute/executor_filter.go
- Introduced support for the text filter that has space in it
- Error message template has changed for filter execution response
Same as [here](https://github.com/kubeshop/botkube/pull/805)
=> v0.15.0 Fixes / Enhancements

pkg/bot/socketslack.go, pkg/execute/executor_filter.go
- This cherry picks the latest v0.15.0 Fixes.
=> Cherry-picked v0.15.0 Fixes / Enhancements (#826)

pkg/config/config.go, pkg/config/config_test.go, pkg/config/testdata/TestLoadedConfigValidationErrors/app-token-only.yaml, pkg/config/testdata/TestLoadedConfigValidationErrors/bot-token-only.yaml, pkg/config/testdata/TestLoadedConfigValidationErrors/missing-executor.yaml, pkg/config/testdata/TestLoadedConfigValidationErrors/missing-source.yaml, pkg/config/testdata/TestLoadedConfigValidationErrors/no-token.yaml, pkg/config/validator.go
* Check that bindings mentioned in Communicators exist
Resolves #760
=> Validate bindings for communcators

helm/botkube/e2e-test-values.yaml, internal/plugin/index.go, internal/plugin/index_test.go, internal/plugin/manager.go, internal/plugin/store.go, internal/plugin/testdata/TestValidateIndexErrors/invalid.yaml, internal/plugin/testdata/TestValidateIndexSuccess/valid.yaml, internal/stringx/indent.go, internal/stringx/indent_test.go, pkg/config/config_test.go, pkg/config/plugin.go, pkg/config/plugin_test.go, pkg/config/testdata/TestLoadedConfigEnabledPluginErrors/bind-diff-repo.yaml, pkg/config/testdata/TestLoadedConfigEnabledPluginErrors/bind-diff-ver-latest.yaml, pkg/config/testdata/TestLoadedConfigEnabledPluginErrors/bind-diff-ver.yaml, pkg/config/testdata/TestLoadedConfigEnabledPluginErrors/cfg-group-diff-repo.yaml, pkg/config/testdata/TestLoadedConfigEnabledPluginErrors/cfg-group-diff-ver.yaml, pkg/config/testdata/TestLoadedConfigEnabledPluginErrors/cfg-group-wrong-plugin-def.yaml, pkg/config/validator.go, pkg/execute/plugin_executor.go
- Add plugin validation for configuration groups, bindings, and index repository
- **BUG**: Return the error message to user when calling the plugin executor
- **BUG**: Resolve plugin also when the exact version is specified
Fix #869
=> Add plugin validation for configuration groups, bindings and index repository

test/e2e/bots_test.go, test/e2e/discord_driver_test.go
Reverts debug log from automatically merged PR
=> Revert changes from auto-merged PR

examples/ingress-recommendations/README.md, examples/ingress-recommendations/botkube-values.yaml, examples/service-debugging/README.md, examples/service-debugging/botkube-values.yaml
- Update docs in example folder
- #802
=> Update docs in example folder

cmd/botkube/main.go, cmd/executor/helm/README.md, helm/botkube/e2e-test-values.yaml, internal/executor/helm/bin_runner.go, internal/executor/helm/commands.go, internal/executor/helm/config.go, internal/executor/helm/executor.go, internal/executor/helm/get.go, internal/executor/helm/history.go, internal/executor/helm/list.go, internal/executor/helm/status.go, internal/executor/helm/test.go, internal/executor/helm/version.go, internal/plugin/manager.go, pkg/bot/interactive/help.go, pkg/bot/interactive/markdown_test.go, pkg/bot/interactive/plaintext_test.go, pkg/bot/interactive/plugin_help.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/execute/help.go, test/e2e/bots_test.go
- Add helm get and history commands
- Add helm info to Botkube help if plugin is enabled
- Describe e2e testing scenario
- Make info plugin not found error more descriptive
- Normalize the Botkube command in header (remove new lines and redundant whitespaces)
Was described in the [helm README.md
](https://github.com/kubeshop/botkube/blob/0652c8c2ebc1ca0e6a8dfd8d38c1ca4a41e44aee/cmd/executor/helm/README.md) file.
Resolves #843
=> Add helm get and history cmds, update Botkube help, add testing scenario, fix bugs

docs/investigation/rbac/README.md, docs/investigation/rbac/assets/clusterrole.yaml, docs/investigation/rbac/assets/clusterrole2.yaml, docs/investigation/rbac/assets/role.yaml, docs/proposal/2022-12-23-rbac.md
- Describe RBAC design proposal
- Add instruction for RBAC PoC
Source code changes for PoC are available in https://github.com/kubeshop/botkube/pull/909.
Resolves #873
=> Describe RBAC design proposal and add instruction for RBAC PoC

helm/botkube/README.md, helm/botkube/values.yaml
- Add helm binding to all bot platforms
=> Add helm binding to all bot platforms

internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
Last occurrence of old `start|stop notifications`
=> start|stop -> enable|disable notifications

cmd/executor/echo/main.go, internal/plugin/index.go
Fixes minor issues spotted by @mszostok
=> Make refURL omitempty

.github/workflows/pr-build.yaml
- fixed goreleaser default tag
=> fix invalid goreleaser tag

.github/PULL_REQUEST_TEMPLATE.md
- Add "Testing" section for PR template
=> Add "Testing" section in pull request template

helm/botkube/README.md, helm/botkube/values.yaml, internal/status/reporter.go, pkg/config/config.go
- Add default remote config provider endpoint
=> Add default remote config provider endpoint

cmd/botkube/main.go, internal/analytics/identity.go, internal/analytics/noop_reporter.go, internal/analytics/reporter.go, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_RegisterCurrentIdentity.json
- Report Deployment ID when using remote configuration
=> Report Deployment ID when using remote configuration

internal/insights/k8s_collector.go, internal/source/prometheus/config.go, internal/source/prometheus/source.go, pkg/api/source/grpc_adapter.go
- Fix logging heartbeat error
- Require providing Prometheus URL
=> Fix logging heartbeat error and require providing Prometheus URL

.github/workflows/upload-plugins.yaml, cmd/botkube/main.go, internal/heartbeat/noop_reporter.go, internal/heartbeat/reporter.go, internal/insights/k8s_collector.go, internal/source/prometheus/config.go, internal/source/prometheus/source.go, pkg/api/source/grpc_adapter.go
- Heartbeat reporting fixed
- Log formatting fixes
- Plugin publish fix
=> 1.0.0-rc1 bug fixes

internal/status/gql_reporter.go
- Report botkube version to remote config source
Relates to https://github.com/kubeshop/botkube-cloud/issues/304
=> report botkube version

internal/source/kubernetes/router.go, pkg/config/manager_remote.go, test/e2e/bots_test.go
- Respect Kubernetes' recommendation settings
Define source with recommendations 
```yaml
sources:
'k8s-recommendation-events':
displayName: "Kubernetes Recommendations"
botkube/kubernetes:
context: *default-plugin-context
enabled: true
config:
namespaces:
include:
- "default"
recommendations:
pod:
noLatestImageTag: true
labelsSet: true
ingress:
backendServiceValid: true
tlsSecretValid: true
```
Check that included namespaces work:
```
$ k delete pod nginx -n default; k run nginx --image=nginx -n default
```
Check that other namespaces are filtered out:
```
$ k delete pod nginx -n botkube; k run nginx --image=nginx -n botkube
```
Override config for `pods`:
```yaml
sources:
'k8s-recommendation-events':
displayName: "Kubernetes Recommendations" …
```
=> Use namespace filter in Recommendations

cmd/executor/gh/main.go, helm/botkube/README.md, helm/botkube/values.yaml, internal/executor/helm/executor.go, internal/executor/helm/executor_test.go, internal/executor/kubectl/executor.go, internal/source/dispatcher.go, internal/source/kubernetes/source.go, pkg/action/provider.go, pkg/action/provider_test.go, pkg/api/source/grpc_adapter.go, pkg/api/source/logger.go, pkg/bot/discord.go, pkg/bot/mattermost.go, pkg/bot/slack.go, pkg/bot/socketslack.go, pkg/bot/teams.go, pkg/execute/executor.go, pkg/execute/factory.go, pkg/pluginx/kubeconfig.go
- Cherry pick bug fixes for 1.0.1-rc.2
This PR will be merged with rebase & merge strategy.
#1057
=> Cherry-pick bug fixes for 1.0.1-rc.2

pkg/execute/params.go
=> Handle --all-clusters flag

cmd/botkube/main.go, pkg/bot/cloudslack.go, pkg/bot/cloudslack_test.go
- Implement retries for Start Cloud Slack func
- Connect Instance and restart Slack Router
=> Implement retries for Start Cloud Slack func

internal/executor/kubectl/builder/deps.go, internal/executor/kubectl/builder/kubectl.go, internal/executor/kubectl/builder/kubectl_test.go, internal/executor/kubectl/executor.go, internal/executor/kubectl/kc_runner.go
- Make sure that `kubectl` uses a proper kubeconfig
=> Make sure that `kubectl` uses a proper kubeconfig

internal/source/scheduler.go, pkg/bot/cloudslack.go, pkg/bot/socketslack.go
- Fix scheduling messages for Cloud Slack
Use the PR image with cloud command:
```
--set image.repository=kubeshop/pr/botkube \
--set image.tag=1108-PR \
```
Resolves https://github.com/kubeshop/botkube/issues/1109
=> Fix scheduling messages for Cloud Slack

cmd/executor/x/main.go
- Fix x plugin schema definition
=> Fix x plugin schema definition

.github/workflows/pr-build.yaml, Makefile, cmd/cli/cmd/docs.go, cmd/cli/cmd/root.go, cmd/cli/docs/botkube.md, cmd/cli/docs/botkube_login.md, cmd/cli/docs/botkube_migrate.md, go.mod, go.sum, internal/cli/frontmatter/format.go
- Add CLI command to generate cobra docs
Run `make gen-docs-cli`
- #1125
=> Add CLI command to generate cobra docs

test/e2e/migration_test.go
- Fix migration test flag
After changing `--debug` to `--verbose` flag in migration CLI (https://github.com/kubeshop/botkube/pull/1134) the job started to fail. This fixes this issue.
=> Fix migration test flag

cmd/cli/cmd/install.go, cmd/cli/cmd/root.go, cmd/cli/cmd/uninstall.go, cmd/cli/docs/botkube.md, cmd/cli/docs/botkube_install.md, cmd/cli/docs/botkube_uninstall.md, internal/cli/helmx/action_cfg.go, internal/cli/install/helm/config.go, internal/cli/install/helm/install.go, internal/cli/install/install.go, internal/cli/printer/status.go, internal/cli/uninstall/config.go, internal/cli/uninstall/helm/config.go, internal/cli/uninstall/helm/uninstall.go, internal/cli/uninstall/uninstall.go
- Add botkube `uninstall` command
Build CLI and install Botkube as described here: https://github.com/kubeshop/botkube/pull/1140
Next run `botkube uninstall`
Fix https://github.com/kubeshop/botkube/issues/1133
=> Add botkube uninstall command

.goreleaser.yml
- Add build flags to CLI
1. `goreleaser release --rm-dist --skip-publish --skip-validate --snapshot`
2. ` ./dist/botkube-cli_darwin_amd64_v1/botkube version -v`
```
▓▓▓ botkube
Version            v9.99.9-dev
Git Commit         a1c420d
Build Date         14 Jul 23 14:11 CEST (1 minute ago)
Commit Date        14 Jul 23 13:52 CEST (19 minutes ago)
Dirty Build        no
Go version         1.19.4
Compiler           gc
Platform           darwin/amd64
```
=> Add build flags to CLI

.goreleaser.yml, cmd/botkube-agent/main.go, cmd/cli/cmd/migrate.go, cmd/cli/docs/botkube_migrate.md, internal/cli/install/helm/install.go, internal/cli/install/logs/json_parser.go, internal/cli/migrate/migrate.go, internal/cli/migrate/opts.go, internal/plugin/index_builder.go, internal/plugin/logger.go, internal/plugin/manager.go, internal/plugin/manager_test.go, test/e2e/migration_test.go
=> Port bug fixes into v1.2

.goreleaser.yml, internal/executor/helm/executor.go, internal/executor/helm/executor_test.go, internal/executor/helm/testdata/TestExecutorHelmInstallHelp.txt
- Remove custom `install` for brew formula
=> Remove custom install for brew formula, fix Helm plugin formatting

internal/cli/install/logs/printer.go
package "github.com/charmbracelet/log" is being imported more than once 
- ...
=> chore: pkg imported more than once

.golangci.yml, hack/fmt-imports.sh, test/commplatform/discord_tester.go, test/commplatform/slack_tester.go, test/e2e/bots_test.go, test/e2e/k8s_helpers_test.go, test/e2e/migration_test.go
- Lint migration test
- Fix reported linter issues
=> Lint migration test

pkg/bot/mattermost.go
- Trim suffix for Mattermost URL
https://github.com/kubeshop/botkube/issues/1107
=> Trim suffix for Mattermost URL

.github/actions/dump-cluster/action.yaml, .github/workflows/branch-build.yml, .github/workflows/pr-build.yaml, .github/workflows/release.yml, .github/workflows/upload-plugins.yaml, .goreleaser.plugin.tpl.yaml, .goreleaser.plugin.yaml, .goreleaser.yml, Makefile, hack/gen-plugin-index.go, hack/goreleaser.sh, hack/target/build-plugins/main.go, internal/plugin/downloader.go, internal/plugin/downloader_test.go, internal/plugin/index_builder.go, internal/plugin/manager.go, internal/plugin/store.go, internal/plugin/testdata/TestGetFirstFileInDirectory/valid_script/script.sh, test/README.md, test/fake/plugin_server.go
- Add support for archived plugins
Integration test are already using archives. However, you can test that also locally by running botkube with local plugins in the same way as you did before.
- https://github.com/kubeshop/botkube-docs/issues/235
=> Add support for archived plugins

cmd/executor/gh/main.go
- Add JSON schema for GitHub reporter plugin
=> Add JSON schema for GitHub reporter plugin

.github/workflows/pr-build.yaml
- New env vars added for e2e tests
=> Introduce environment variables for Cloud Slack E2E tests

.github/workflows/branch-build.yml, .github/workflows/pr-build.yaml, test/commplatform/slack_tester.go
- Remove slack bot username override
=> Remove Slack bot user name from CI by default

pkg/bot/mattermost.go
In order to fix ticket #1177, the way users are fetched has to change in order to include bot accounts. 
- Change `getBotUserID` to use `GetUsersByUsernames` and `GetTeamMember` instead of  relying on `AutocompleteUsersInTeam`. 
Fixes #1177
=> Support bot accounts for Mattermost

cmd/cli/cmd/config/get.go, cmd/cli/cmd/migrate.go, internal/cli/config/get.go, internal/cli/install/iox/stdout.go, internal/cli/printer/dynamic_spinner.go, internal/cli/printer/status.go
- Fix printing steps when file redirect is used
`botkube config get > /tmp/config.yaml`
=> Fix printing steps when file redirect is used

.github/workflows/pr-build.yaml
- Fix PR build workflow indentation
=> Fix PR build workflow indentation

internal/executor/doctor/executor.go
- Support custom OpenAI API endpoint for Doctor plugin
Resolves https://github.com/kubeshop/botkube/issues/1188
=> Support custom OpenAI API params for Doctor plugin

cmd/cli/cmd/install.go, cmd/cli/cmd/uninstall.go, cmd/cli/docs/botkube_install.md, cmd/cli/docs/botkube_uninstall.md, internal/source/argocd/config-jsonschema.json
- Fix spelling for CLI docs
- Fix JSON schema for ArgoCD source plugin
https://github.com/kubeshop/botkube-docs/pull/280
=> Fix JSON schema for ArgoCD source plugin and spelling for CLI docs

.golangci.yml, internal/plugin/kubeconfig.go, internal/source/argocd/argocd.go, internal/source/argocd/config-jsonschema.json, internal/source/argocd/default-config.yaml, internal/source/argocd/req-jsonschema.json, internal/source/argocd/setup_notifications.go, internal/source/argocd/setup_notifications_test.go, internal/source/incoming_webhook.go
- Fix JSON schema for ArgoCD
- Tested against Botkube Cloud UI
- Fix not generating Kubeconfig if both mappings are empty
- Fix normalizing names during ArgoCD notifications setup
Use instruction from https://github.com/kubeshop/botkube/pull/1220, but instead of `argocd` source config name, try to use something longer, e.g. `my-custom-argocd`. Use the name both in Helm chart and the values.yaml for overrides.
#1175
=> Fix ArgoCD notification setup and JSON schema

go.mod, go.sum, helm/botkube/templates/deployment.yaml, helm/botkube/templates/global-config.yaml, internal/source/argocd/argocd.go, internal/source/argocd/config.go, internal/source/argocd/setup_notifications.go, internal/source/incoming_webhook.go, internal/source/scheduler.go
- Fix marshalling `oncePer` trigger property for ArgoCD source
- Fix setting incoming webhook details by envs; we cannot use global config as they need to be also set for remote config case.
- Fix duplicated messages for incoming requests for the same source bound multiple times 
#989
=> Fix duplicated messages for incoming requests and marshalling `oncePer` trigger property for ArgoCD source

pkg/bot/slack_cloud.go
- Fix writing on closed channel in Cloud Slack
Resolves https://github.com/kubeshop/botkube/issues/1241
=> Fix writing on closed channel in Cloud Slack

.github/workflows/ci.yml, internal/config/remote/config.go, internal/source/kubernetes/recommendation/resource_events_test.go, internal/source/kubernetes/router_test.go
- Fix issues reported by linter
- Update linter to the newest version
=> Fix issues reported by linter

.github/ISSUE_TEMPLATE/feature_request.md
- Add demo video to the Acceptance Criteria for feature requests
#1180
=> Add demo video to the Acceptance Criteria for feature requests

.github/workflows/publish-chart.yml
=> fix chart repo url

test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go, test/helmx/helm_helpers.go
- Main charts are published periodically. Now we use that charts in tests
=> Use main chart in tests

internal/executor/thread-mate/config.go, internal/executor/thread-mate/jsonschema.json, pkg/bot/slack_socket.go, pkg/config/config.go
- Update thread-mate schema, fix setting emoji indicator
=> Update thread-mate schema, fix setting emoji indicator

.github/workflows/publish-chart.yml
- added workflow dispatch to be able to generate chart manually
=> workflow dispatch

pkg/bot/interactive/markdown.go, pkg/bot/interactive/markdown_test.go, pkg/bot/interactive/plaintext.go
- Made md formatter fields public
=> md formatter change

.github/workflows/prod-e2e-test.yml
- Added new env variable for organization id for prod e2e test
=> Added new org env var for prod e2e test

test/helmx/helm_helpers.go
- Handled empty repository URL to use the default one. Default one is provided already here https://github.com/kubeshop/botkube/blob/6c853734270d9b06df9f98b078b74d00c403cb7d/test/e2e/migration_test.go#L41
=> ignore empty botkube repositories url during cli test

README.md, internal/remote/graphql/models_gen.go
- Update GraphQL models used for remote config tests
- Fix small typo in Readme
The tests for Cloud Slack are failing because of outdated models: https://github.com/kubeshop/botkube/actions/runs/7450570079/job/20270862350?pr=1344
This PR fixes it.
No need to test it - CI pipeline will verify it.
=> Update GraphQL models used for remote config tests

.github/workflows/prod-e2e-test.yml
- Run the Cloud Slack E2E test every hour
=> Run the Cloud Slack E2E test every hour

.github/workflows/branch-build.yml, test/README.md, test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
- Update Slack E2E tests with full workspace reconnect flow
CI tests it. See:
- https://github.com/kubeshop/botkube/actions/runs/7527418846/attempts/4
- https://github.com/kubeshop/botkube/actions/runs/7527418846/job/20495645184
=> Update Slack E2E tests with full workspace reconnect flow

README.md
Updated with new wording and integration pages.
- Update Readme
=> Update README.md with new description

.github/workflows/branch-build.yml, test/e2e/migration_test.go
=> Migration tests

.github/workflows/branch-build.yml
- Fix branch-build.yml workflow, see: https://github.com/kubeshop/botkube/actions/runs/7723558493/job/21054338344
=> Fix branch-build.yml workflow

cmd/botkube-agent/main.go
=> Fix a tiny typo

.github/workflows/branch-build.yml, helm/botkube/README.md, helm/botkube/templates/service.yaml, helm/botkube/templates/systemroles.yaml, helm/botkube/values.yaml, internal/cli/migrate/converter.go, pkg/config/config.go, pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml, pkg/execute/config_test.go, test/e2e/migration_test.go
- Fix migration CI job
- Ensure plugin version is removed when migrating to Cloud
- Remove unused Lifecycle server properties
Just spotted some old properties which aren't used for a while.
No need to test it.
=> Fix migration CI job and remove unused `lifecycleServer` properties

test/e2e/bots_test.go
- Fix executor assertion for integration tests
This is caused by the migration update on dev. During first startup of Botkube, we're dropping the plugin version. That's why we need to update the assertion.
=> Fix executor assertion for integration tests

helm/botkube/README.md, helm/botkube/values.yaml, internal/analytics/segment_reporter.go, internal/analytics/segment_reporter_test.go, internal/analytics/testdata/TestSegmentReporter_ReportPluginsEnabled.json, internal/executor/kubectl/executor.go, internal/source/kubernetes/config_schema.json
=> Apply patches for 1.9.1

.github/workflows/prod-e2e-test.yml
- Run Cloud Prod E2E tests every 2 hours
=> Run Cloud Prod E2E tests every 2 hours

test/commplatform/teams_tester.go, test/e2e/bots_test.go
-  Fix Teams integration tests assertions
CI pipelines:
- `#1` https://github.com/kubeshop/botkube/actions/runs/8597146561/job/23555982688?pr=1429
- `#2` https://github.com/kubeshop/botkube/actions/runs/8597146561/job/23557157920?pr=1429
- `#3` https://github.com/kubeshop/botkube/actions/runs/8598488153/job/23559481339?pr=1429
Fix https://github.com/kubeshop/botkube/issues/1423
=> Fix Teams integration tests assertions

pkg/api/message.go, pkg/bot/interactive/help.go, pkg/bot/slack_renderer.go, test/msg-layouts/help_test.go, test/msg-layouts/testdata/TestNewHelpMessage/cloud-slack-help.golden.json, test/msg-layouts/testdata/TestNewHelpMessage/cloud-teams-help.golden.json
- Add information about storing mentions and event in audit logs
- https://github.com/kubeshop/botkube-cloud/issues/875
After merging https://github.com/kubeshop/botkube-cloud/pull/1050 I will need to sync it back to `botkube` repo, to make the e2e test pass.
=> Add information about storing mentions and event in audit logs

pkg/plugin/kubeconfig.go
=> fix: close temporary kubeconfig file

helm/botkube/Chart.yaml, helm/botkube/README.md, helm/botkube/values.yaml, pkg/bot/slack_cloud.go, pkg/bot/slack_socket.go
- Update Helm chart description and error wording
=> Update Helm chart description and error wording

helm/botkube/README.md, helm/botkube/README.tpl.md
- Update Helm chart Readme rendering for new docs page
It is required by the MDX parser on our Docusaurus v3 docs.botkube.io.
See also: https://github.com/kubeshop/botkube-docs/pull/334
=> Update Helm chart Readme links rendering

.github/actions/cloud-slack-e2e/action.yaml, .github/actions/dump-cluster/action.yaml
=> Update GitHub actions

.github/actions/cloud-slack-e2e/action.yaml, .github/workflows/branch-build.yml, .github/workflows/prod-e2e-test.yml
- Add missing UI URL for prod tests
=> Add missing UI URL for prod tests
